### ISSUE TITLE
lavavu/glucifer server side rendering enhancements

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#105]
1. Currently the interactive server side rendering option (accessed via the 'open_viewer' method), starts a server which publishes to localhost:someport.  This is problematic for docker cloud usage, as we can't a priori know which ports will be available, and a static port is not an option as there will at times be multiple instances (for multiple users) running on the single machine. Is it possible instead to publish to some different address on the same port?  Then perhaps each docker container would simply publish everything to port 80 perhaps, and then this would be mapped as necessary to different ports for each user. 

2. It would be good to have an option to run the server side rendering inside an embedded window, ala the webgl viewer.

**Comment by lmoresi** [comment]
We might have to adopt the poxy server that Tim suggested - in which we can intercept specific ports and publish them all to the docker side in one hit.

It looks complicated but they do it for the DIT4c images all the time.

L


On 8 April 2016 at 11:24:23 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

  1.  Currently the interactive server side rendering option (accessed via the 'open_viewer' method), starts a server which publishes to localhost:someport. This is problematic for docker cloud usage, as we can't a priori know which ports will be available, and a static port is not an option as there will at times be multiple instances (for multiple users) running on the single machine. Is it possible instead to publish to some different address on the same port? Then perhaps each docker container would simply publish everything to port 80 perhaps, and then this would be mapped as necessary to different ports for each user.

  2.  It would be good to have an option to run the server side rendering inside an embedded window, ala the webgl viewer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/105>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by jmansour** [comment]
Just realised we have a glucifer ticket we can put this in. #87
