### ISSUE TITLE
mesh_deform aware particle escape

### ISSUE THREAD

**Issue by garethkennedy** [underworldcode/underworld2#108]
Minimum version of compression example. Xmin/max boundaries are mobile but the ymin/max are fixed. Swarm particles should exit the domain in the top centre - they don't which causes the error to be thrown.
If the ymax boundary is moved such that the particles are always inside the domain then it runs. My understanding is that the population control for the swarm should remove them without needing the ymax to move.
FYI, the extension model works without moving the ymax.

[Compression.zip](https://github.com/underworldcode/underworld2/files/214286/Compression.zip)

**Comment by lmoresi** [comment]
I'm having this problem too. I have set the flag for particles to escape the domain and I can see that the escaped routine is being called. But there is no way to call the escaped routine after updating the mesh which is obviously where the problem arises.

If I manually shift the particles back into the domain and call the particle owners routines, I still have problems. There is obviously some sync issue that we need to look at carefully.

**Comment by jmansour** [comment]
This seems to be an issue with coupled mesh/swarm advection. Definitely something we'll need to tackle when we implement mesh advection proper.  

I think Louis' suggestion to implement particle advection via a mesh advection proxy might be useful here. 

Let's keep track of this via #69

**Comment by lmoresi** [comment]
John,

I don't think that would be a panacea. We may well have genuine reasons to move the mesh and cull particles lying outside (e.g. erosion models). We need to be able to do that elegantly (or inelegantly, but explicitly). Right now there doesn't seem to be a way to call the particle escape routines other than during advection. 

I'm not re-opening this issue because I think the compression example I checked in serves as a workaround to this particular issue which we could fix by mesh advection or virtual mesh advection. 

Maybe we need an A.L.E. issue to track.

**Comment by jmansour** [comment]
Ok, i'll re-open.   

I'm not exactly sure what's the best interface to this.  We could easily add some pre/post hooks to the mesh_deform context manager.  The swarms could then add routines to these hooks at construction time.

**Comment by jmansour** [comment]
As per yesterday's discussion, added pre/post hooks to deform_mesh CM.  If your swarm has particleEscape enabled, your particles outside the domain will be culled during the post CM hook. 

ffc99719751801a15d1fed61fe8dfcf3193b926d
