### ISSUE TITLE
How does the physical parameters scaled in UW2?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#111]
I suppose in underworld2 code all the variables such as temperature, velocity, length and time, etc are in non-dimensional value. But I wonder how can I transform these parameters into dimensional values. What are the scalings for these parameters?

**Comment by jmansour** [comment]
At this stage there is no explicit concept of units or scaling in underworld2.  This may be implemented at a later stage, or may not.  

So the values are simply as you set them, and you can use dimensional or non-dimensional values.

**Comment by wkillers** [comment]
So for example if I want to set the height of the box to be 1000km, I can just set h=1 to represent 1000km, or I can set h=1e6 for which the unit is meter. But for numerical solvers, is it always better to set h=1 rather than h=1e6?

**Comment by lmoresi** [comment]
We leave the choice to the user but it is good numerical practice to keep values close to 1 if you can. There is no one best / foolproof way to scale models so we don't have it built in. We will try to get some examples together though and post a note in the blog.

Sent from my iPhone

On 14 Apr 2016, at 00:43, Yongming Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


So for example if I want to set the height of the box to be 1000km, I can just set h=1 to represent 1000km, or I can set h=1e6 for which the unit is meter. But for numerical solvers, is it always better to set h=1 rather than h=1e6?

**Comment by RebeccaFarrington** [comment]
@rbeucher covers this in a blog post

[Using physical units in Underworld](http://www.underworldcode.org/posts/ScalingPhysicalUnits)
