### ISSUE TITLE
Speed of advect v solve for deforming mesh

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#112]
@jmansour   -  can you add more details?

**Comment by jmansour** [comment]
Yes I can!  So, in uw-retro, we had a cheeky little hack that allowed for a faster owning cell search for deformed mesh.  Basically it started the search from the previous owning cell, whereas currently we start the search from the cell with the middle local index.   

Again, this is for deformed mesh.. where the mesh is cartesian, we use much faster regular-mesh routines as opposed to the drunken walk search (/newborn giraffe walk / drunken stiletto walk).  

My proposed solution is the expose the global coord -> (local coord, elementId) routine as a Function™.  This function can then optionally also take a _hint_ function which for swarms might provide the previous owning cell.

**Comment by lmoresi** [comment]
The mirko's walk algorithm is not directed and not guaranteed to visit each cell only once ... so this seems like a very poor algorithm for finding a particle.

I don't think the other algorithm is really a cheeky hack at all given that we choose a timestep which ensures that the particles haven't moved very much. If the mesh is actively deforming as well due to boundary conditions then we have a similar restriction on how many cells a typical particle will traverse.

The troublesome case is where the mesh-movement is arbitrary (e.g. for mesh refinement) - especially if we end up re-partitioning. But that is easily fixed - for irregular meshes, we might have to use scipy which is chock full of kd-tree algorithms for doing fast searches on grids.

L





________________________________

**Comment by jmansour** [comment]
I didn't mean cheeky in its logic, just in its implementation.

**Comment by lmoresi** [comment]
That's what happens when you write code in the hot tub I suppose.




________________________________

**Comment by julesghub** [comment]
Well said louis. I think the previous "cheeky" solution was quite
reasonable and we should have that functionality back again for default
deformed meshes....but the implementation was a hottub disaster for which I
am to blame ;)

John, the proposed solution essentially recreates the cheeky algorithm
right?
Also with the general proposed solution. What are other "hint functions" it
could take? IJK search

**Comment by lmoresi** [comment]
Does the projection functionality enable you to do SPR ? I am not sure if the requirement for C1 continuity is built in ?

Sent from my iPhone

On 19 Apr 2016, at 17:37, julesghub <notifications@github.com<mailto:notifications@github.com>> wrote:

Well said louis. I think the previous "cheeky" solution was quite
reasonable and we should have that functionality back again for default
deformed meshes....but the implementation was a hottub disaster for which I
am to blame ;)

John, the proposed solution essentially recreates the cheeky algorithm
right?
Also with the general proposed solution. What are other "hint functions" it
could take? IJK search

**Comment by lmoresi** [comment]
kdtree

**Comment by julesghub** [comment]
I threw in the cheeky solution with a somewhat-nicer implementation.
https://github.com/underworldcode/underworld2/commit/c3be1e4e6e07f350f67bf032ba5e2be4482fdc07
This significantly speeds up evaluate(swarm) and advection within non-regular meshes.
I thought I'd throw this now because currently particles+deformed mesh models are painfully slow.
I still believe other implementations of the problem should be explored.

**Comment by rbeucher** [comment]
+1 for KdTree but the cheeky solution is more than welcomed for now...!
