### ISSUE TITLE
Careful chronologies for provided examples

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#117]
We need to be more careful about the point at which we save data (for viz, checkpoint, or analysis).  Currently, we often have something like this:

```python
while time<timeEnd:
    solver.solve()
    dt = advector.get_max_dt()
    advector.integrate(dt)
    if steps%outputEvery == 0:
        velocityField.save('vel'+str(steps)+".h5")
        swarm.save('swarm'+str(steps)+'.h5')        
    time += dt
    steps += 1
```

However in this case, the saved swarm does not actually correspond to the velocity field, but instead corresponds to the velocity field at t+1.  We should have something like this

```python
while time<timeEnd:
    solver.solve()
    if steps%outputEvery == 0:
        velocityField.save('vel'+str(steps)+".h5")
        swarm.save('swarm'+str(steps)+'.h5')        
    dt = advector.get_max_dt()
    advector.integrate(dt)
    time += dt
    steps += 1
```

And for checkpoint restarts, we probably want something like this:

```python
if not checkpoingRestart:
    # do some initialisation
else:
    velocityField.load('..')
    swarm.load('..')
    etc....
    # now update everything because we already have complete info for the reloaded step
    dt = advector.get_max_dt()
    advector.integrate(dt)
    time += dt
    steps += 1
   
   
while time<timeEnd:
    solver.solve()
    if steps%outputEvery == 0:
        velocityField.save('vel'+str(steps)+".h5")
        swarm.save('swarm'+str(steps)+'.h5')        
    dt = advector.get_max_dt()
    advector.integrate(dt)
    time += dt
    steps += 1
```

This is especially important for the examples, as people are going to simply cut/paste what we have provided.

**Comment by lmoresi** [comment]
Agreed - this became obvious with the moving mesh examples where the vis would pull values from out of the mesh etc.

There is probably no general safe solution since we have an operator split in time / space.

L

Sent from my iPhone

On 18 Apr 2016, at 17:53, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


We need to be more careful about the point at which we save data (for viz, checkpoint, or analysis). Currently, we often have something like this:

while time<timeEnd:
    solver.solve()
    dt = advector.get_max_dt()
    advector.integrate(dt)
    if steps%outputEvery == 0:
        velocityField.save('vel'+str(steps)+".h5")
        swarm.save('swarm'+str(steps)+'.h5')
    time += dt
    steps += 1

However in this case, the saved swarm does not actually correspond to the velocity field, but instead corresponds to the velocity field at t+1. We should have something like this

while time<timeEnd:
    solver.solve()
    if steps%outputEvery == 0:
        velocityField.save('vel'+str(steps)+".h5")
        swarm.save('swarm'+str(steps)+'.h5')
    dt = advector.get_max_dt()
    advector.integrate(dt)
    time += dt
    steps += 1

And for checkpoint restarts, we probably want something like this:

if not checkpoingRestart:
    # do some initialisation
else:
    velocityField.load('..')
    swarm.load('..')
    etc....
    # now update everything because we already have complete info for the reloaded step
    dt = advector.get_max_dt()
    advector.integrate(dt)
    time += dt
    steps += 1


while time<timeEnd:
    solver.solve()
    if steps%outputEvery == 0:
        velocityField.save('vel'+str(steps)+".h5")
        swarm.save('swarm'+str(steps)+'.h5')
    dt = advector.get_max_dt()
    advector.integrate(dt)
    time += dt
    steps += 1

**Comment by jmansour** [comment]
351e26b6f971d681675cb27f809571042f9bd7ae

note that only the models in the 'examples' directory have been updated.
