### ISSUE TITLE
Building error with the latest development branch

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#119]
Some errors appear when using ./scons.py to build the code with the latest version of development branch:
```
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading Conscript files.

scons: Building targets ...
Compiling ==> libUnderworldPy/Underworld_wrap.cxx
libUnderworldPy/Underworld_wrap.cxx:12871:7: error: use of undeclared identifier '_SUPGVectorTerm_NA__Fn_SetFn'
      _SUPGVectorTerm_NA__Fn_SetFn(arg1,arg2);
      ^
libUnderworldPy/Underworld_wrap.cxx:28560:21: error: no member named 'cppdata' in 'AdvDiffResidualForceTerm'
  if (arg1) (arg1)->cppdata = arg2;
            ~~~~~~  ^
libUnderworldPy/Underworld_wrap.cxx:28583:30: error: no member named 'cppdata' in 'AdvDiffResidualForceTerm'
  result = (void *) ((arg1)->cppdata);
                     ~~~~~~  ^
3 errors generated.
scons: *** [build/libUnderworldPy/Underworld_wrap.os] Error 1
scons: building terminated because of errors.
```

**Comment by lmoresi** [comment]
These sound like problems due to the swig wrappers being out of date. I think we still recommend that this is done manually - scons doesn't do this at the moment (probably)

Sent from my iPhone

On 21 Apr 2016, at 18:04, Yongming Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


Some errors appear when using ./scons.py to build the code with the latest version of development branch:

scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading Conscript files.

scons: Building targets ...
Compiling ==> libUnderworldPy/Underworld_wrap.cxx
libUnderworldPy/Underworld_wrap.cxx:12871:7: error: use of undeclared identifier '_SUPGVectorTerm_NA__Fn_SetFn'
      _SUPGVectorTerm_NA__Fn_SetFn(arg1,arg2);
      ^
libUnderworldPy/Underworld_wrap.cxx:28560:21: error: no member named 'cppdata' in 'AdvDiffResidualForceTerm'
  if (arg1) (arg1)->cppdata = arg2;
            ~~~~~~  ^
libUnderworldPy/Underworld_wrap.cxx:28583:30: error: no member named 'cppdata' in 'AdvDiffResidualForceTerm'
  result = (void *) ((arg1)->cppdata);
                     ~~~~~~  ^
3 errors generated.
scons: *** [build/libUnderworldPy/Underworld_wrap.os] Error 1
scons: building terminated because of errors.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/119>

**Comment by wkillers** [comment]
But I did this ./scons.py before I use ./swigall.py to build the swig wrappers

**Comment by jmansour** [comment]
There should now be a `compile.sh` command.  You should always use that instead.   Or just use dockers.

**Comment by wkillers** [comment]
Thanks.
