### ISSUE TITLE
compilation of underworld2 with out HDF5 parallel?

### ISSUE THREAD

**Issue by geofarhan** [underworldcode/underworld2#140]
Hi,

I would like to ask you about compilation of underworld2. Can I compile underworld2 with out HDF5 parallel. Our institute cluster does not have HDF5 parallel module. 

Thanks in advance. 
Farhan

**Comment by lmoresi** [comment]
It’s non-negotiable, unfortunately.

It’s not too hard to install though. And the more recent versions of hdf5 are parallel by default so it may just be a question of pushing your admins for an upgrade.

L


On 30 May 2016 at 8:21:33 pm, geofarhan (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi,

I would like to ask you about compilation of underworld2. Can I compile underworld2 with out HDF5 parallel. Our institute cluster does not have HDF5 parallel module.

Thanks in advance.
Farhan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/underworldcode/underworld2/issues/140>, or mute the thread<https://github.com/notifications/unsubscribe/AMAXox1oh8bo9nUMogwhvtH6JLeVWfiOks5qGromgaJpZM4IprMd>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by geofarhan** [comment]
Thanks for your comment!

I'm trying to install on another cluster machine which has HDF5 parallel libraries.

Thanks
Farhan
