### ISSUE TITLE
Direct Solvers

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#146]
What's the best practice for building the code against the parallel direct solvers (superludist and mumps?)

* Will these both be supported in future?
* Do these simply depend on how the PETSC installation is built?
* Do flags at the ./configure.py stage play any role?

Thanks

**Comment by lmoresi** [comment]
Entirely through PETSc, dan.

Mumps, in particular, is almost standard because PETSc generally does a great job of installing it.

L

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>


On June 7, 2016 at 7:10:09 PM, Dan Sandiford (notifications@github.com<mailto:notifications@github.com>) wrote:

What's the best practice for building the code against the parallel direct solvers (superludist and mumps?)

  *   Will these both be supported in future?
  *   Do these simply depend on how the PETSC installation is built?
  *   Do flags at the ./configure.py stage play any role?

Thanks

**Comment by dansand** [comment]
Thanks Louis, I think I just needed to upgrade my homebrew to get mumps working  - i'll leave this issue open for a couple more hours so I can post anything useful for homebrew users.

**Comment by lmoresi** [comment]
Homebrew has trouble whenever there are system updates that affect compilers.  Their insistence on adopting everything new immediately is not very robust.



---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>


On June 7, 2016 at 8:55:38 PM, Dan Sandiford (notifications@github.com<mailto:notifications@github.com>) wrote:

Thanks Louis, I think I just needed to upgrade my homebrew to get mumps working - i'll leave this issue open for a couple more hours so I can post anything useful for homebrew users.
