### ISSUE TITLE
debug v optimised

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#148]
What is the typical performance difference?  Currently the default is debugging (also used for generate dockers).  

Naturally debugging is useful for developers, but should users use debug as default?  Where are there extra safety checks performed in debug mode, and is it perhaps better to switch these out to runtime options?  Something like

```python
import underworld as uw
uw.safe = True
```

**Comment by OKaluza** [comment]
Here's the numbers from my single proc test run of slab subduction example that I mentioned in email:

**108sec** debug
**72sec** optimised

Only a very basic test, but 50% faster is nothing to laugh at, I would suggest --with-debugging=0 for all builds on clusters and docker images.

Agree that any safety checks that are in place for users rather than developers (ie: checking for invalid inputs) should not be compiled out.

**Comment by lmoresi** [comment]
Debug off in the master branch, on in the dev branch ?




On 10 June 2016 at 10:51:55 AM, OKaluza (notifications@github.com<mailto:notifications@github.com>) wrote:

Here's the numbers from my single proc test run of slab subduction example that I mentioned in email:

108sec debug
72sec optimised

Only a very basic test, but 50% faster is nothing to laugh at, I would suggest --with-debugging=0 for all builds on clusters and docker images.

Agree that any safety checks that are in place for users rather than developers (ie: checking for invalid inputs) should not be compiled out.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/underworldcode/underworld2/issues/148#issuecomment-225067907>, or mute the thread<https://github.com/notifications/unsubscribe/AMAXo-rsWBsK10DEanALISV6iF1sUnSAks5qKLUhgaJpZM4IxqDK>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Docker images are now built without debugging.  Release version will use optimised as default (this will be listed as an action in the release guidelines).  Dev version will retain debugging/non-optimised modes.
