### ISSUE TITLE
solver errors not being captured in python layer

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#158]
While running some simulations, mumps encountered some errors which it reported to standard output (which is not seen when running within notebooks). The simulation however continued, though the results were clearly wrong. 

We really need to be capturing these solver errors and throw an exception so that the user is aware of any potential issues.

**Comment by lmoresi** [comment]
Also - if mumps is not installed petsc returns garbage results and carries on in a very British fashion as though nothing happened !

==========
Louis Moresi
==========

On 11 Aug 2016, at 9:55 AM, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


While running some simulations, mumps encountered some errors which it reported to standard output (which is not seen when running within notebooks). The simulation however continued, though the results were clearly wrong.

We really need to be capturing these solver errors and throw an exception so that the user is aware of any potential issues.

**Comment by julesghub** [comment]
Going #235

**Comment by julesghub** [comment]
To consider for uw3.
