### ISSUE TITLE
Extract velocity field maximum at boundary 

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#169]
I'm trying to get the velocity field Max at the surface. This is the implementation, it works in serial, but returns `nan` in parallel:

    velxfn = fn.view.min_max(velfield[0])
    velxfn.evaluate(mesh.specialSets["MaxJ_VertexSet"])
    return velxfn.max_global()

**Comment by jmansour** [comment]
cheers dan. the issue here is that for your given function input, some processors don't get hit at all.  it's a bug in any case.

662eea2d94e5875a503089addb9f92acb21db6e4

this fix is on 2.1.0b which will be merged back into dev next week.. but you can just switch over to that branch for now if you need the fix asap (it's basically the same as dev).
