### ISSUE TITLE
Install on Centos 6

### ISSUE THREAD

**Issue by esmm2016** [underworldcode/underworld2#185]
Dear colleagues,

I am trying to install Underworld2, but I always get the same error.

 ./configure.py
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... yes
Checking for package libPNG... yes
Checking for package gl2ps... no
Checking for package X11... yes
Checking for package OpenGL... yes

Saved configuration: "config.cfg"
  C compiler:     'mpicc'
  C flags:        -g -O0 -Wall
  C preprocessor: ['HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'DEBUG']
  Libraries: ['python2.6', 'hdf5', 'xml2', 'm', 'petsc']

Saved configuration: "graphics.cfg"
  C preprocessor: ['HAVE_LIBPNG', 'HAVE_X11', 'HAVE_OPENGL', 'DEBUG']
  Libraries: ['GL', 'GLU', 'X11', 'png']

*****************************************************************
* Successfully configured.                                      *
*                                                               *
* Note that basic usage metrics are dispatched when you use     *
* Underworld.                                                   *
* To opt out, set the UW_NO_USAGE_METRICS environment variable. *
* See PRIVACY.md for full details.                              *
*                                                               *
* Now run './compile.py' to build.                                *
*****************************************************************

When I do: ./compile.py or ./scons.py:
./scons.py                                          scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> Solvers/KSPSolvers/src/BSSCR/BSSCR.c
In file included from /usr/include/python2.6/pyconfig.h:6,
                 from /usr/include/python2.6/Python.h:8,
                 from build/include/StGermain/Base/Context/Variable.h:14,
                 from build/include/StGermain/Base/Context/Context.h:18,
                 from build/include/StGermain/Base/Base.h:19,
                 from build/include/StGermain/StGermain.h:17,
                 from Solvers/KSPSolvers/src/BSSCR/BSSCR.c:32:
/usr/include/python2.6/pyconfig-64.h:1034:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/stdlib.h:25,
                 from Solvers/KSPSolvers/src/BSSCR/BSSCR.c:9:
/usr/include/features.h:213:1: warning: this is the location of the previous definition
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPSolve_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:225: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:225: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPSetFromOptions_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:298: warning: passing argument 1 of 'PetscOptionsHead' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:216: note: expected 'struct PetscOptionItems *' but argument is of type 'struct _n_PetscOptions **'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:302: warning: passing argument 1 of 'PetscOptionsEnum_Private' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:271: note: expected 'struct PetscOptionItems *' but argument is of type 'struct _n_PetscOptions **'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:304: error: request for member 'count' in something not a structure or union
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPSetUp_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:335: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:335: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:346: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:346: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:359: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:359: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:368: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:368: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:376: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:376: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPCreate_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:413: warning: assignment from incompatible pointer type
scons: *** [build/Solvers/KSPSolvers/src/BSSCR/BSSCR.os] Error 1
scons: building terminated because of errors.

I installed PETSc like this: 
./configure
make all test

Do you have any idea to help me?
Thank you in advance.
Regards.

**Comment by lmoresi** [comment]
That looks like a PETSc version problem - we support 3.5.x and 3.6.x but changes in the interface from version to version mean that it takes some time to write and test a compatibility layer.

Which PETSc versions do you have access to ?

L


On 23 November 2016 at 2:36:21 AM, esmm2016 (notifications@github.com<mailto:notifications@github.com>) wrote:

Dear colleagues,

I am trying to install Underworld2, but I always get the same error.

./configure.py
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... yes
Checking for package libPNG... yes
Checking for package gl2ps... no
Checking for package X11... yes
Checking for package OpenGL... yes

Saved configuration: "config.cfg"
C compiler: 'mpicc'
C flags: -g -O0 -Wall
C preprocessor: ['HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'DEBUG']
Libraries: ['python2.6', 'hdf5', 'xml2', 'm', 'petsc']

Saved configuration: "graphics.cfg"
C preprocessor: ['HAVE_LIBPNG', 'HAVE_X11', 'HAVE_OPENGL', 'DEBUG']
Libraries: ['GL', 'GLU', 'X11', 'png']

________________________________

  *   Successfully configured. *
  *

                                                          *


  *   Note that basic usage metrics are dispatched when you use *
  *   Underworld. *
  *   To opt out, set the UW_NO_USAGE_METRICS environment variable. *
  *   See PRIVACY.md for full details. *
  *

                                                          *


  *   Now run './compile.py' to build. *

________________________________

When I do: ./compile.py or ./scons.py:
./scons.py scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> Solvers/KSPSolvers/src/BSSCR/BSSCR.c
In file included from /usr/include/python2.6/pyconfig.h:6,
from /usr/include/python2.6/Python.h:8,
from build/include/StGermain/Base/Context/Variable.h:14,
from build/include/StGermain/Base/Context/Context.h:18,
from build/include/StGermain/Base/Base.h:19,
from build/include/StGermain/StGermain.h:17,
from Solvers/KSPSolvers/src/BSSCR/BSSCR.c:32:
/usr/include/python2.6/pyconfig-64.h:1034:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/stdlib.h:25,
from Solvers/KSPSolvers/src/BSSCR/BSSCR.c:9:
/usr/include/features.h:213:1: warning: this is the location of the previous definition
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPSolve_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:225: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:225: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPSetFromOptions_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:298: warning: passing argument 1 of 'PetscOptionsHead' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:216: note: expected 'struct PetscOptionItems *' but argument is of type 'struct _n_PetscOptions **'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:302: warning: passing argument 1 of 'PetscOptionsEnum_Private' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:271: note: expected 'struct PetscOptionItems *' but argument is of type 'struct _n_PetscOptions **'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:304: error: request for member 'count' in something not a structure or union
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPSetUp_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:335: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:335: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:346: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:346: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:359: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:359: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:368: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:368: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:376: warning: passing argument 3 of 'PetscOptionsGetBool' from incompatible pointer type
/export/apps/petsc/include/petscoptions.h:15: note: expected 'const char *' but argument is of type 'enum PetscBool *'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:376: error: too few arguments to function 'PetscOptionsGetBool'
Solvers/KSPSolvers/src/BSSCR/BSSCR.c: In function 'KSPCreate_BSSCR':
Solvers/KSPSolvers/src/BSSCR/BSSCR.c:413: warning: assignment from incompatible pointer type
scons: *** [build/Solvers/KSPSolvers/src/BSSCR/BSSCR.os] Error 1
scons: building terminated because of errors.

I installed PETSc like this:
./configure
make all test

Do you have any idea to help me?
Thank you in advance.
Regards.

**Comment by esmm2016** [comment]
Ok, thanks but I installed PETSC 3.5.4 and changed the error:

 ./scons.py
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> Underworld/Function/src/IOIterators.cpp
In file included from /usr/include/python2.6/pyconfig.h:6:0,
                 from /usr/include/python2.6/Python.h:8,
                 from Underworld/Function/src/IOIterators.hpp:14,
                 from Underworld/Function/src/IOIterators.cpp:10:
/usr/include/python2.6/pyconfig-64.h:1034:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/x86_64-redhat-linux/bits/os_defines.h:40:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/x86_64-redhat-linux/bits/c++config.h:2058,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/iosfwd:40,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/ios:39,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/istream:40,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/sstream:39,
                 from Underworld/Function/src/IOIterators.cpp:9:
/usr/include/features.h:162:0: note: this is the location of the previous definition
In file included from /usr/include/python2.6/pyconfig.h:6:0,
                 from /usr/include/python2.6/Python.h:8,
                 from Underworld/Function/src/IOIterators.hpp:14,
                 from Underworld/Function/src/IOIterators.cpp:10:
/usr/include/python2.6/pyconfig-64.h:1043:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/x86_64-redhat-linux/bits/os_defines.h:40:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/x86_64-redhat-linux/bits/c++config.h:2058,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/iosfwd:40,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/ios:39,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/istream:40,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/sstream:39,
                 from Underworld/Function/src/IOIterators.cpp:9:
/usr/include/features.h:164:0: note: this is the location of the previous definition
In file included from Underworld/Function/src/IOIterators.cpp:10:0:
Underworld/Function/src/IOIterators.hpp:72:9: error: 'NpyIter' does not name a type
Underworld/Function/src/IOIterators.hpp:73:9: error: 'NpyIter_IterNextFunc' does not name a type
Underworld/Function/src/IOIterators.cpp: In constructor 'Fn::NumpyInput::NumpyInput(PyObject*, FunctionIO::IOType)':
Underworld/Function/src/IOIterators.cpp:58:32: error: class 'Fn::NumpyInput' does not have any field named '_iter'
Underworld/Function/src/IOIterators.cpp:58:45: error: class 'Fn::NumpyInput' does not have any field named '_iternext'
Underworld/Function/src/IOIterators.cpp: In member function 'virtual void Fn::NumpyInput::reset()':
Underworld/Function/src/IOIterators.cpp:75:9: error: '_iter' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:76:33: error: 'NpyIter_Deallocate' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:81:5: error: '_iter' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:81:48: error: 'NPY_ITER_READONLY' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:82:32: error: 'NPY_ITER_EXTERNAL_LOOP' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:83:32: error: 'NPY_ITER_REFS_OK' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:84:32: error: 'NPY_KEEPORDER' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:84:47: error: 'NPY_UNSAFE_CASTING' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:84:73: error: 'NpyIter_New' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:91:5: error: '_iternext' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:91:48: error: 'NpyIter_GetIterNext' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:93:33: error: 'NpyIter_Deallocate' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:98:45: error: 'NpyIter_GetDataPtrArray' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:100:51: error: 'NpyIter_GetInnerStrideArray' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:102:54: error: 'NpyIter_GetInnerLoopSizePtr' was not declared in this scope
Underworld/Function/src/IOIterators.cpp: In member function 'virtual Fn::NumpyInput& Fn::NumpyInput::operator++(int)':
Underworld/Function/src/IOIterators.cpp:138:31: error: '_iter' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:138:36: error: '_iternext' was not declared in this scope
Underworld/Function/src/IOIterators.cpp: In destructor 'virtual Fn::NumpyInput::~NumpyInput()':
Underworld/Function/src/IOIterators.cpp:147:9: error: '_iter' was not declared in this scope
Underworld/Function/src/IOIterators.cpp:148:33: error: 'NpyIter_Deallocate' was not declared in this scope
scons: *** [build/Underworld/Function/src/IOIterators.os] Error 1
scons: building terminated because of errors.

My: gcc --version
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thank you in advance.
Regards.

**Comment by jmansour** [comment]
You may need a more recent version of Numpy.  I believe at least 1.8.

**Comment by esmm2016** [comment]
Well, thanks but change error:
./scons.py
Compiling ==> gLucifer/Viewer/src/Main/main.cpp
In file included from gLucifer/Viewer/src/Main/../Include.h:60:0,
                 from gLucifer/Viewer/src/Main/../Util.h:38,
                 from gLucifer/Viewer/src/Main/../Geometry.h:37,
                 from gLucifer/Viewer/src/Main/../TimeStep.h:39,
                 from gLucifer/Viewer/src/Main/../DrawState.h:6,
                 from gLucifer/Viewer/src/Main/../LavaVu.h:39,
                 from gLucifer/Viewer/src/Main/main.cpp:36:
gLucifer/Viewer/src/Main/../json.hpp: In instantiation of 'nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::basic_json(std::initializer_list<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType> >, bool, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::value_t) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator]::<lambda(const nlohmann::basic_json<>&)>':
gLucifer/Viewer/src/Main/../json.hpp:1667:54:   required from 'struct nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::basic_json(std::initializer_list<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType> >, bool, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::value_t) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator]::<lambda(const class nlohmann::basic_json<>&)>'
gLucifer/Viewer/src/Main/../json.hpp:1667:13:   required from 'nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::basic_json(std::initializer_list<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType> >, bool, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::value_t) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator]'
gLucifer/Viewer/src/Main/../DrawState.h:97:41:   required from here
gLucifer/Viewer/src/Main/../json.hpp:1669:17: error: 'using object_t = class std::map<std::basic_string<char>, nlohmann::basic_json<>, std::less<std::basic_string<char> >, std::allocator<std::pair<const std::basic_string<char>, nlohmann::basic_json<> > > >' has no member named 'emplace'
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/algorithm:63:0,
                 from gLucifer/Viewer/src/Main/../Include.h:24,
                 from gLucifer/Viewer/src/Main/../Util.h:38,
                 from gLucifer/Viewer/src/Main/../Geometry.h:37,
                 from gLucifer/Viewer/src/Main/../TimeStep.h:39,
                 from gLucifer/Viewer/src/Main/../DrawState.h:6,
                 from gLucifer/Viewer/src/Main/../LavaVu.h:39,
                 from gLucifer/Viewer/src/Main/main.cpp:36:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/bits/stl_algo.h:4436:5: error: '_Funct std::for_each(_IIter, _IIter, _Funct) [with _IIter = const nlohmann::basic_json<>*; _Funct = nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::basic_json(std::initializer_list<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType> >, bool, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::value_t) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator]::<lambda(const nlohmann::basic_json<>&)>]', declared using local type 'nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::basic_json(std::initializer_list<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType> >, bool, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::value_t) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator]::<lambda(const nlohmann::basic_json<>&)>', is used but never defined [-fpermissive]
scons: *** [build/gLucifer/Viewer/main.os] Error 1
scons: building terminated because of errors.

thank you very much for your help
Regards.

**Comment by jmansour** [comment]
It seems that gcc 4.7.2 is missing some required features:
http://stackoverflow.com/questions/15812276/stdset-has-no-member-emplace

You might need gcc 4.8+

**Comment by esmm2016** [comment]
Ok, thanks but I installed gcc 4.8.2 and changed the error:

./scons.py
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading SConscript files.
scons: Building targets ...
Linking Program ==> build/bin/LavaVu
/usr/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
scons: *** [build/bin/LavaVu] Error 1
scons: building terminated because of errors.

Thank you in advance.
Regards.

**Comment by esmm2016** [comment]
I solved the problem reinstalling SWIG.
Thank you very much to everyone for your help!

**Comment by jmansour** [comment]
great!  btw, are you the compiling on a hpc type machine, or on a desktop?
