### ISSUE TITLE
simple example code for elasticity problem

### ISSUE THREAD

**Issue by cenguo** [underworldcode/underworld2#188]
Hi Underworldians ,

I wish to use underworld2 for elastoplastic solid mechanics problems. The current examples for me to start with are all solving Stokes equations. Can anyone provide me a simple code solving quasi-static equilibrium equation with elastic material?

My another concern is the comparison of FEMLIP with MPM. It seems in order to obtain good integration result, ~50 particles were assigned to each element in the examples. However, only 4 material points are used for each grid in MPM (similar to FEM). Does that mean the efficiency of FEMLIP is much lower than MPM?

Many thanks,
Ning

**Comment by jmansour** [comment]
Hi Ning.  We will have an example with viscoelasticity in the next release (hopefully), which should be just around the corner. 

In Underworld you have two options for integration:  the voronoi lagrangian integration point scheme, or standard FEM gauss integration.  For the latter, when you are using particles, currently it simply utilises a near neighbour approach to determine values at the gauss points. 

Also, we currently default to using 9 (or 27 in 3d) particles per element.. this is mainly so that where we have lagrangian particles, we sufficiently sample their types. It is also required for higher order elements. 

In terms of efficiency, the cost of integration is usually very small relative to the other costs (in particular the solve time), so it should usually not be a concern. 

I'll leave this open as a reminder for us to add the elastoplastic example.

**Comment by RebeccaFarrington** [comment]
Little correction - there is currently a viscoelastic example committed, `/docs/examples/2_11_ViscoelasticityInSimpleShear.ipynb`
 Cheers,
Rebecca

**Comment by jmansour** [comment]
Thanks Bec!  I don't think we can give a useful timeline for a model also including plasticity, so I will close this ticket for now.   Please check in with us again at a later date!
