### ISSUE TITLE
State of director method anisotropic viscosity

### ISSUE THREAD

**Issue by cgoise** [underworldcode/underworld2#198]
Hi,
this is certainly not a proper 'issue' for the issue tracker, but in absence of better alternatives this might be the best place for my question. Sorry for polluting this channel, but I hadn't had luck getting information about this from other sources.

I would like to model an anisotropic viscous material (orthotropic/transversely isotropic). There is a jupyter notebook tagged as 'under development' in the repo (master and devel) which will do almost that when it's finished (the TransOrthoModel-Compression script).

The question is: what exactly is here under development?? Is only the notebook-code under development, but the functionality is generally already implemented? Or is the whole thing under development? I feel confident to develop a python code from the ground up, but it would be nice if I could start this on the basis of a fully functional framework. As an outsider I find it hard to evaluate this from the github-code.

And if implemented, is this also already part of the current docker image? I'm facing the same trouble compiling the code from the repo as some others on the issue tracker, so this would be a great.

Thanks!

**Comment by lmoresi** [comment]
I think this one is fine to open as an issue ! The implementation itself is mature, the interface at the python level is basic. The implementation of all non-linear / plasticity models is now at the python level and we haven't put an example together to demonstrate that yet. But we do have them.

**Comment by jmansour** [comment]
Just to expand on this, we currently have this available as hidden/private parameters to the `uw.systems.Stokes` constructor.  Check the `_fn_viscosity2` and `_fn_director` parameters here:

http://underworld2.readthedocs.io/en/latest/underworld.systems.html#underworld.systems.Stokes

As @lmoresi mentioned, the implementation at the C level is mature, but we are yet to finalise the interface to this at the python level (and also add documentation/tests/etc), and that is why it's set as private. The notebooks are tagged under development because they use private features, and also because they still, well, under development. 

So we would encourage you to use it (and give us feedback!), but keep in mind that it is still experimental and there may be issues and/or changes. 

You should be able to access it via any of the recent docker images.

**Comment by cgoise** [comment]
To know that the core implementation is fully functional is the most important thing atm. The examples should then suffice to get things started, I suppose. Thank you, and be sure to get feedback.

**Comment by jmansour** [comment]
No probs!  I'll close this ticket for now, but feel free to reopen if necessary.
