### ISSUE TITLE
broken models

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#20]
Hey folks 

I've moved many models into docs/development/broken.  These are models that either don't run to completion without issue, or that I wasn't sure were producing the correct results.  

So if your models are here and you wish to retain them, please check that they run to completion and produce correct results.  Also tidy them if necessary :-).  Once satisfied, you can move them into docs/tutorials or docs/tests, and set permissions to read-only.  

If they are tutorial style, Gareth & Rebecca have devised a fancy style guide for reference!

If you do not wish to retain them, remove them. 

For info on what belongs where, naming conventions, and other novelties, check docs/development/guidelines.md.

**Comment by lmoresi** [comment]
OK - I’ll get around to fixing the notebooks up as soon as I can.

The guidelines should be a bit more explicit about what they are referring to … if they are for developers of the python code or the user guides. I would suggest we have a developer section of the docs for the experts and this could be somewhere that John and Julian leave notes for

And let’s keep updating the website to reflect the changes that are being made here.
“Casual" browsing will not take people deep into the repo to find this sort of information.

L


On 14 October 2015 at 10:35:52 PM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Hey folks

I've moved many models into docs/development/broken. These are models that either don't run to completion without issue, or that I wasn't sure were producing the correct results.

So if your models are here and you wish to retain them, please check that they run to completion and produce correct results. Also tidy them if necessary :-). Once satisfied, you can move them into docs/tutorials or docs/tests, and set permissions to read-only.

If they are tutorial style, Gareth & Rebecca have devised a fancy style guide for reference!

If you do not wish to retain them, remove them.

For info on what belongs where, naming conventions, and other novelties, check docs/development/guidelines.md.

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/20>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by jmansour** [comment]
Not sure I quiet understand louis.  The guidelines.md file is for the developer group.  

Some info in there is useful for users (where to find things, what is in user relevant directories), but this should go in the top level readme.

**Comment by lmoresi** [comment]
There are three different “developer” communities - one is notebook developers and that is almost entirely overlapping with the users. The other would be developers of the python code. Some of the notes are clearly aimed at them because I think the notebook / ipython style guide might be a bit harder to enforce (tabs / spaces seem to be interpreted by the browser and so on). The C / C++ level is another thing again … psychologically damaged individuals needing lots of rehabilitation.

I would like us to have guidelines for each of these groups in the relevant locations.

My main concern is that the web pages should be updated to match these files because I am worried that we are somehow expecting people to work out how things operate by looking through the repo. I know from my experience that it is hard to start using a code if it is repository-only.

L


On 16 October 2015 at 10:02:23 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Not sure I quiet understand louis. The guidelines.md file is for the developer group.

Some info in there is useful for users (where to find things, what is in user relevant directories), but this should go in the top level readme.

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/20#issuecomment-148547137>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by jmansour** [comment]
This document is really meant to be for the Underworld API development group (ie, us!). It's a work in progress, but the aim is to provide guidelines for all aspects of the API development: coding (c/c++/python), API documentation (docstrings & user guide), usage examples (tutorials scripts & notebooks), version control, etc.  While some more involved end users might find it useful, I don't think the information here should go on the website. 

Most information relevant to end users should go in the user guide. Seeing as github is kind enough to render jupyter notebooks for us, the web site user guide page should simply link to the required github repo files:

[07. Visualisation with gLucifer](https://github.com/underworldcode/underworld2/blob/development/docs/user_guide/Visualisation%20with%20gLucifer.ipynb)

We won't be winning any design awards, but it does ensure that the information is always up to date.  Also, it shows end users where the files are located and allows them to switch between different versions of the documentation. 

The web site could likewise provide a link to the tutorials (or simply a link to the directory on github).

The top level readme.txt will contain lower level information relevant to users. It is rendered at github repo landing page.  

All in all I think this keeps us pretty well covered.  Importantly, it avoids any duplication of content which is always a nightmare from a maintenance perspective.

**Comment by lmoresi** [comment]
Ok - the other distinguishing factor is that the developer docs are all restructured text. Probably that should be the case for this file extension so it renders properly.

Sent from my iPhone

On 17 Oct 2015, at 06:49, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


This document is really meant to be for the Underworld API development group (ie, us!). It's a work in progress, but the aim is to provide guidelines for all aspects of the API development: coding (c/c++/python), API documentation (docstrings & user guide), usage examples (tutorials scripts & notebooks), version control, etc. While some more involved end users might find it useful, I don't think the information here should go on the website.

Most information relevant to end users should go in the user guide. Seeing as github is kind enough to render jupyter notebooks for us, the web site user guide page should simply link to the required github repo files:

07. Visualisation with gLucifer<https://github.com/underworldcode/underworld2/blob/development/docs/user_guide/Visualisation%20with%20gLucifer.ipynb>

We won't be winning any design awards, but it does ensure that the information is always up to date. Also, it shows end users where the files are located and allows them to switch between different versions of the documentation.

The web site could likewise provide a link to the tutorials (or simply a link to the directory on github).

The top level readme.txt will contain lower level information relevant to users. It is rendered at github repo landing page.

All in all I think this keeps us pretty well covered. Importantly, it avoids any duplication of content which is always a nightmare from a maintenance perspective.

**Comment by julesghub** [comment]
Closing for now - see docs/development/guidelines.md for details regarding this discussion
