### ISSUE TITLE
Internal heating

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#21]
Hi devs. Just thought I'd interrupt quality day by throwing this one in there. If someone can get around do adding internal heating soon, I'd be really happy.

**Comment by lmoresi** [comment]
I would second this, it is an important part of the basic functionality.

I would also suggest (preaching to the converted, I know) that this too should be a function since it needs to depend on material and, for long-running simulations, on time. It would also depend on melting history …

L


On 21 October 2015 at 2:26:18 PM, Dan Sandiford (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi devs. Just thought I'd interrupt quality day by throwing this one in there. If someone can get around do adding internal heating soon, I'd be really happy.

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/21>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
It's there already for the steady state system. For the supg, there are some subtleties, but I believe Mirko was on top of the details.

**Comment by lmoresi** [comment]
How about for the Semi-Lagrange scheme ?  That might end up being more straightforward.

L




On 22 October 2015 at 8:50:20 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

It's there already for the steady state system. For the supg, there are some subtleties, but I believe Mirko was on top of the details.

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/21#issuecomment-150035134>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Yep, i believe it should be much easier.

**Comment by julesghub** [comment]
It's the SL currently available in python?

**Comment by jmansour** [comment]
no it's not.  wouldn't be a huge job to get it moving.

**Comment by julesghub** [comment]
@mirkovelic what's the status?

**Comment by OlympusMonds** [comment]
+1 on this

**Comment by julesghub** [comment]
Internal heating fix coming very soon

**Comment by jmansour** [comment]
any progress here?

**Comment by julesghub** [comment]
The internal heating fix for SUPG was folded in with the recent merge of the flux conditions branch. Update the dev branch and look at the documentation for defining the advectiondiffusion system in python.

So far so good for me so I'm closing this ticket.
