### ISSUE TITLE
swarm load very slow on large sims with deformed mesh 

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#211]
Basically, we do swarm reloads serially.  Each processor considers *every* particle for ownership.  This is clearly not scalable, but it might not be an issue if the cost is still relatively small.. unfortunately I'm getting reports of 4 hour restart times.

Our checkpointed files do not record any information about the partitioning of the simulation used to generate them.  This decouples them from the simulation partitioning, which is good, but perhaps we should also record particle processor ownership in a sidecar file which can then be leveraged for restarts using identical proc counts (ie, 99% of the time). This will make restarts lightning quick, except where they are done using different proc counts, in which case we revert to the current (slow) behaviour.

**Comment by julesghub** [comment]
Interesting, is the time being taken up by the h5py read or the
add_particle routine. If h5py is the colprit perhaps we can change the
default chunking size.

**Comment by jmansour** [comment]
It's a good question.  Perhaps our friends at NCI might be able to shed some light on this shortly.

**Comment by julesghub** [comment]
Actually I just saw now that you are talking about 'deformed' meshes.
So my assume the add_particles routine is the problem.

When Romain and I recently used swarms in a deformed mesh we found the
default search algorithm was very very slow, i.e. CellLayout_CellOf()
We used the idea of leveraging the previous OwningCell to speed it up. This
work is on the swarmSpeedup branch and is quite good (~50x speed up for
advecting swarms)
In the restart-from-checkpoint setting this may not make much sense unless
the discretisation is exactly the same.

**Comment by jmansour** [comment]
What was the change?  Did you use the previous cell as the init guess?  There must be some sort of smarter algorithm out there to assist with these type of problems... some sort of tree based data structure... hmm

In the restart from checkpoint case, i'd elect to record the owning proc & cell for _immediate_ restart without figuring who owns what.

**Comment by julesghub** [comment]
On 31 March 2017 at 10:07, jmansour <notifications@github.com> wrote:

> What was the change? Did you use the previous cell as the init guess?
> There must be some sort of smarter algorithm out there to assist with these
> type of problems... some sort of tree based data structure... hmm
>
Yes we used the previous cell as the init guess. Big speed up!
I suppose the kdtree idea, using element centroids as the vertices would be
a more general approach.

> In the restart from checkpoint case, i'd elect to record the owning proc &
> cell for *immediate* restart without figuring who owns what.
>
Agreed

**Comment by rbeucher** [comment]
The default search algorithm is very slow as it explore the domain by always starting from its center. 
When you run in parallel, the domains on each proc are usually quite small so it does the job...So my guess is when you revert back to serial for some operations on a large domain you get a huge difference because you are wasting time travelling through the whole domain.
So our idea was to use information from the previous step so that we know roughly where to look for...
KD-tree are more general but I suspect they won't be faster. They might actually be slower...

We usually start with an initially regular mesh so I think the current fix is good enough...

**Comment by lmoresi** [comment]
Kdtree is faster in totally unstructured cases after about 100 or so points but I was more thinking about the serial case - because it has a culling algorithms for distance, I can see it being quite quick if handed all the particles in the domain and having to grab only the ones for the given proc.

Sent from my iPhone

On 31 Mar 2017, at 11:09, rbeucher <notifications@github.com<mailto:notifications@github.com>> wrote:


The default search algorithm is very slow as it explore the domain by always starting from its center.
When you run in parallel, the domains on each proc are usually quite small so it does the job...So my guess is when you revert back to serial for some operations on a large domain you get a huge difference because you are wasting time travelling through the whole domain.
So our idea was to use information from the previous step so that we know roughly where to look for...
KD-tree are more general but I suspect they won't be faster. They might actually be slower...

We usually start with an initially regular mesh so I think the current fix is good enough...

**Comment by jmansour** [comment]
How about we simply write an array into the swarm checkpoint file, which records the per proc counts (or offsets), and then each processor can simply start reading the particles at required position.   

This way, we only increase the swarm checkpoint file slightly, and where restarting with identical proc counts, each processor should read all its particles first (and therefore only read its files).   Where restarting with different proc counts, we revert to the current behaviour.

**Comment by julesghub** [comment]
I have implemented Mansour's suggestions here
578cb2a0727b0a80d52f0ed5adf398175ad6e015
9633fd7e5ffeb36d57e0c153ee3f7482e3857fcf

to be in the 2.3 release.
Processor offset particle counts are now saved with swarm checkpoint file. This speeds up load time.
It can still lead to mistakes when reloading the particles, ie if mesh discretisation/decomposition is different between the saved state.
One can disable the use of offsets at load time, reverting back to the brute force algorithm, using the arg 'try_optimised'. ie,  swarm.load(filename, try_optimised=False). For backwards compatibility this is the behaviour when loading swarm checkpoint files that don't contain the proc offsets.

Moving forward a bounding extremes check per proc should be added.
