### ISSUE TITLE
Memory leak when using Augmented Lagrangian K2 Method

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#215]
When setting a penalty value, and thus using the Augmented Lagrangian K2 Method, I noticed that we get a warning:

`swig/python detected a memory leak of type 'Vec *', no destructor found.`

I am having some memory issues, which might be completely unrelated, but looks like some destructors are missing.

I have started to investigate using the Raylegh Taylor example... @jmansour @julesghub  could you have a look?

R

**Comment by lmoresi** [comment]
This one is a long-lived problem and there is a prize of a can of Toohey’s red for the finder because it baffled Mirko.

Not many things baffled Mirko (except the real world).

L



On 28 April 2017 at 8:55:15 am, rbeucher (notifications@github.com<mailto:notifications@github.com>) wrote:

When setting a penalty value, and thus using the Augmented Lagrangian K2 Method, I noticed that we get a warning:

swig/python detected a memory leak of type 'Vec *', no destructor found.

I am having some memory issues, which might be completely unrelated, but looks like some destructors are missing.

I started to investigate using the Raylegh Taylor example... @jmansour<https://github.com/jmansour> @julesghub<https://github.com/julesghub> could you have a look?

R

**Comment by rbeucher** [comment]
ahaha!! I should not waste too much time on that then...Not that I could not do with a can of Toohey’s red...

**Comment by jmansour** [comment]
I wouldn't worry about that swig message.  We do not rely on swig to generate or implicitly call destructors for petsc vec objects.  

Are you actually noticing memory usage increasing with runtime?

**Comment by rbeucher** [comment]
Yes I am... We should discuss that at some point...

**Comment by lmoresi** [comment]
We should simplify that penalty code.

Much of it is there for reasons of testing / evaluation and can go (like the second K matrix, not needed in real life).

L



On 28 April 2017 at 10:38:27 am, rbeucher (notifications@github.com<mailto:notifications@github.com>) wrote:

Yes I am... We should discuss that at some point...

**Comment by mirkovelic** [comment]
I don't recall being "baffled" by this....real world excepted.

**Comment by jmansour** [comment]
let's keep all memory leak related banter in this one ticket: #220
