### ISSUE TITLE
glucifer 

### ISSUE THREAD

**Issue by yanghappy1991** [underworldcode/underworld2#230]
I updated my underworld to recent version days ago, but now I cannot use the interactive view of glucifer.  Some command like this:
if not glucifer.lavavu: raise KeyboardInterrupt #Stop notebook here if no vis enabled
lv = figVelocityField_I.viewer()
lv.rotate('z', 90)
lv.rotate('x', -45)
lv.redisplay()

This will not show any figure on the screen. SO what's the new command for display of interactive plotting

**Comment by OKaluza** [comment]
Hi @yanghappy1991 , sorry about that! I only just noticed this issue.

Due to changing the way a number of things work behind the scenes, viewer() now only returns a reference to the viewer object but doesn't display anything yet, to create an interactive window you can either use window() or call .show() on the object returned by viewer()
```python
#viewer() returns the LavaVu viewer object
lv = figVelocityField_I.viewer()
lv.show()
```
or
```python
#window() returns viewer object and displays interactive viewer window in a single command
lv = figVelocityField_I.window()
```
