### ISSUE TITLE
Visualisation on HPC machines

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#233]
We should think about how we're going to do this.

Currently glucifer isn't used on nci/raijin or pawsey/magnus. Data is dumped to h5 then rendered locally using glucifer, paraview, etc. It's not efficient moving big amounts of data around and it's not always possible to render large data sets locally. 

A workflow/fit needs to be sorted out.
I'm going to assign this to Owen, Romain & myself.

**Comment by OKaluza** [comment]
So these are the existing options:

- Efficient use of glucifer and using glucifer.Store() to create database files for transfer to local machine for visualisation - this means staying away from dumping out large numbers of particles when plotting the swarm, either by masking/filtering and using isosurfaces/volumes renders/cross sections to keep the database size per time step small enough to quickly transfer. The databases store vis data in single precision float (half the size of HDF5 data) and are zlib compressed (another 30-90% size saving).
 - Use Mesa on the cluster: this requires the admin to install an up to date version of the Mesa OpenGL libraries and configure it correctly, it needs to be a recent version of Mesa (10+) and preferably compiled with llvmpipe support (which means it will use all the cores on a node to do the rendering, without which creating images can be very slow).

These two options are not equal in functionality either, the first allows full control over the visualisation and ability to script up a vis notebook to create interactive and dynamic plots.
This second way limits you to rendering images remotely of baked in visualisations you have prepared in advance but there is no ability to change anything after the run without the saved databases.

If there was a fast networked data store that was accessible by the cluster nodes and also accessible from a Nectar VM or some other visualisation capable machine, the data files could be saved to this store and visualised elsewhere without having to manually transfer files.  
This kind of thing is becoming more available and is the future for solving these sorts of big data problems where transfers are prohibitively expensive. Many of the newer supercomputing resources can be allocated as Nectar VMs instead of by traditional queue based systems. You can create a Nectar volume storage that you could have your simulation output to, and then boot up a GPU powered virtual machine to run vis on the same data store. (This setup is not yet available on the systems you listed though AFAIK)

**Comment by OKaluza** [comment]
Progress on this: I have built a faster version of Mesa for image output on Raijin (https://github.com/OKaluza/LavaVu/wiki/Headless-rendering#building-mesa-llvmpipe-on-nci-raijin) it is available in /projects/Underworld/mesa-17.1.5

See updated install guide https://github.com/underworldcode/underworld2/blob/development/docs/install_guides/nci_raijin.sh

This means you can produce images on Raijin and it should be fast enough to not hold up the job for minutes as the system Mesa version does (ie: ~0-5 seconds per figure)

I still think the database workflow is more powerful and better but recognise it's really useful to get the image output as well and there is still a lack of tutorial notebooks for this workflow.

**Comment by RebeccaFarrington** [comment]
Thanks for looking into this Owen.
I’ll have a look later this week :)

**Comment by OKaluza** [comment]
There is also now an Underworld 2.3.0 module on Raijin that includes the above Mesa build:
`module load underworld/2.3.0`

**Comment by RebeccaFarrington** [comment]
excellent!  Thanks :)
