### ISSUE TITLE
glucifer on raijin

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#246]
I’ve had a look at lucifer on raijin - thanks for having a look into this @OKaluza  :)

On the login node I get the following results - using the OzBenchEtAl-2008.ipynb exported as a py, with no changes, i.e. low res for 2 time steps.

1. Underworld module builds (underworld/2.3.0). OzBenchEtAl-2008.py runs fine, producing a gldb, png and h5 files.  I need to transfer the gldb to my local machine to run OzBenchEtAl-2008-fig3.  Running OzBenchEtAl-2009-fig3 on raijin produces the following. 

> [rjf565@raijin6 01:39 PM] OzBenchEtAl-2008-module $ python OzBenchEtAl-2008-fig3.py 
> --------------------------------------------------------------------------
> An MPI process has 
> ....
> you may disable this warning
> by setting the mpi_warn_on_fork MCA parameter to 0.
> --------------------------------------------------------------------------
> Traceback (most recent call last):
>   File "OzBenchEtAl-2008-fig3.py", line 24, in <module>
>     saved = glucifer.Viewer('/home/565/rjf565/+Codes/Tests/20170807/OzBenchEtAl-2008-development/ozBench.gldb', quality=3)
>   File "/apps/underworld/2.3.0/underworld2/glucifer/_glucifer.py", line 895, in __init__
>     figname = str(state["figure"])
> KeyError: 'figure'

2. Underworld2-development - clean git checkout on dev branch (today). Following the instructions in the install_guides, it complies but I get the following error.  I imagined this is because it doesn’t have --with-graphics=1 for configure, when this is included I’m told "OpenGL not found, graphics disabled, skipping LavaVu buildOpen”.  I have followed the install instructions, for have OPENGL_LIB and OPENGL_INC flags - I suppose I’m still missing something.

> [rjf565@raijin6 01:25 PM] OzBenchEtAl-2008-development $ python OzBenchEtAl-2008.py 
> --------------------------------------------------------------------------
> An MPI process has executed an operation involving a call to the
> ...
> by setting the mpi_warn_on_fork MCA parameter to 0.
> --------------------------------------------------------------------------
> LavaVu visualisation module load failed: No module named _LavaVuPython
> No module named _LavaVuPython LavaVu module not found! disabling inline visualisation
> 	Global element size: 16x8x16
> 	Local offset of rank 0: 0x0x0
> 	Local range of rank 0: 16x8x16
> Traceback (most recent call last):
>   File "OzBenchEtAl-2008.py", line 132, in <module>
>     figMaterialLayout = glucifer.Figure( figsize=(800,400), quality=2 )
>   File "/home/565/rjf565/+Codes/underworld2-development/glucifer/_glucifer.py", line 401, in __init__
>     self.db = Store()
>   File "/home/565/rjf565/+Codes/underworld2-development/underworld/_stgermain.py", line 110, in __call__
>     _setup()
>   File "/home/565/rjf565/+Codes/underworld2-development/glucifer/_glucifer.py", line 152, in _setup
>     if lavavu and not os.path.isfile(self._lvbin):
> NameError: global name 'lavavu' is not defined

3. The install guide now includes the following.  I get the following error, I imagine I’m missing something!

> #Run this before using underworld glucifer image output 
> #(creates a virtual display)
> Xvfb :0 -screen 0 1600x1200x16&

> [rjf565@raijin6 01:19 PM] +Codes $ Xvfb :0 -screen 0 1600x1200x16&
> [1] 4197
> [rjf565@raijin6 01:19 PM] +Codes $ (EE) 
> Fatal server error:
> (EE) Server is already active for display 0
> 	If this server is no longer running, remove /tmp/.X0-lock
> 	and start again.
> (EE) 
> ^C
> [1]+  Exit 1                  Xvfb :0 -screen 0 1600x1200x16

4. Running on 4 processors, using the underworld/2.3.0 module. I need to comment out the figMaterialStrain.show() and figMaterialStrain.save() - i.e. I can use glucifer, but not any output - png or gldb.

Any comments or thoughts on these would be great :)

Cheers,
Bec

**Comment by ssduarte** [comment]
Hi, 
I'm also having troubles. Early this week I was able to run my model fine on raijin, but since yesterday I'm getting errors like

> (...)
> sh: error importing function definition for `BASH_FUNC_module'
> [r2199:23111] 95 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
> [r2199:23111] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
> 
> 
> =====================================================================================
> Error running Underworld - Signal 11 
> 
> =====================================================================================
> Error running Underworld - Signal 11 'SIGSEGV' (Segmentation Fault).
> This is probably caused by an illegal access of memory.
> We recommend running the code in a debugger to work out where the problem is (e.g. 'gdb')
> and also to contact the developers.
> (...)

I'm wondering if any significant changes were made in the meantime, because now I'm also having troubles using my underworld built using the instructions on the install guide, even though I get no error messages if running in the login node

Cheers
Sílvia

**Comment by OKaluza** [comment]
Hi Silvia, nothing significant has changed and even if it had it would only cause you problems if you updated and rebuilt the code. It sounds like you are having issues running Undworld2 jobs from pbs scripts but not on the login node? Perhaps send through the error logs from the runs and we can try and find what's going on.

Hi Bec, looked into all your issues, mostly easy fixes except # 2 which is odd...
1. The problem here is you are trying to run the OzBenchEtAl-2008-fig3 file from the bleeding edge development version of Underworld2 with the raijin Underworld 2.3.0 module, some changes made since the release in development to improve re-vis mean this won't work, you'll have to either use the version of OzBenchEtAl-2008-fig3.ipynb from "master" or use your own development build of underworld which supports the changes.

2. I just tried building from scratch from a clean checkout and everything works fine here, perhaps it's a permissions issue, can you see the files in the OpenGL build I shared? try running:
`ls /projects/Underworld/mesa-17.1.5/build/linux-x86_64/gallium/targets/libgl-xlib/`

3. As serious as it sounds that error is harmless, just means Xvfb is already running so it can't start another copy. It is because you have loaded the underworld/2.3.0 module which runs Xvfb for you, once it is running it stays running on that node until you log out. In your batch scripts you will need to add the command to run it because it needs to be running on the root node of your job, not just the login node. (Unless you use the underworld/2.3.0 module which runs it for you).

4. See issue https://github.com/underworldcode/underworld2/issues/241 it was fixed soon after the release, but didn't make it into the module unfortunately. You can use glucifer for image output but plotting isosurfaces with a colour field is broken in parallel.

**Comment by RebeccaFarrington** [comment]
Hi @OKaluza!

Thanks for looking into these issues.
1.  Roger that - you are correct, all working.
2. It seems to be resolved now, I no longer get the issue. Although the difference is (perhaps/obviously) including the full PYTHONPATH, i.e. in my case 
`export PYTHONPATH=$HOME/underworld2-developement:$HOME/underworld2-developement/glucifer:/projects/Underworld/opt:`


3. Roger that!  I've included the Xvfb command in my pbs script
4. Roger that - it's working on the uw2-development branch, using the Xvfb command in my pbs script.

Thanks again
