### ISSUE TITLE
fn.value

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#249]
Does the function.value concept extend to more complicated functions (i.e. branching functions)?

Say I want a function that takes the value 1 within a certain radius of a point, and zero everywhere else. Now I want to change that point. Can I used fn.value to update the function, or do I need to rebuild it?

**Comment by jmansour** [comment]
All functions are immutable, except the `Constant` function!!  It's the Mansour Paradox.  Actually, I think we'll rename the `Constant` function to `Parameter` (as per @lmoresi's suggestion) at some stage.

Now, to your question, you could certainly create a branching function which utilises a `Constant` function to define the point, and then change the `Constant` function later.  Something like this:

https://gist.github.com/jmansour/79f36dac29f243e492e20fdc497169ef

**Comment by dansand** [comment]
I think that provides enough flexibility for what I'm after. Thanks!

**Comment by dansand** [comment]
Just posting some follow up to this discussion, looking at how mutable functions interact with integrals and views..

https://github.com/dansand/issues/blob/master/function_mutation/functions_mutable_integral.ipynb

**Comment by lmoresi** [comment]
Wondering if “Coefficient” might also be a candidate for the renaming.

I suggested to Julian that we use the mutable nature of these entities to build the null-space function instead of promoting arbitrary call-backs.




On 25 August 2017 at 2:22:59 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

All functions are immutable, except the Constant function!! It's the Mansour Paradox. Actually, I think we'll rename the Constant function to Parameter (as per @lmoresi<https://github.com/lmoresi>'s suggestion) at some stage.

Now, to your question, you could certainly create a branching function which utilises a Constant function to define the point, and then change the Constant function later. Something like this:

https://gist.github.com/jmansour/79f36dac29f243e492e20fdc497169ef

**Comment by jmansour** [comment]
Yeah I think that all looks right Dan.  

The thing to always remember with the min_max, is that the min/max recorded is obtained simply by inspecting the function evaluation results as they occur.  So if a bunch of evaluations are performed, and then the _image_ of the function is changed (via the `.value` property on the function or one of its subfunctions), the min/max recorded won't change until further evaluations are performed, and only if those evaluations exceed the existing min/max.  As you mention, it may make sense to call `reset()` before you do further evaluations.
