### ISSUE TITLE
sticky-air related issues

### ISSUE THREAD

**Issue by QwZhang** [underworldcode/underworld2#26]
Hi all,
Sorry for disturbing again. I find something wired when I ran a subduction model. 

1. First of all, I find abnormally high value of StressField (isolated sharp peaks in fig.pre1) on the boundarys between domains(shapes). Can anybody explain why I cannot get more smooth value (it should be as such)? 
![fig geometry](https://cloud.githubusercontent.com/assets/12026068/10882984/e9b04464-81a9-11e5-8e6e-424e8e63372f.jpg)
![fig stresstensor3](https://cloud.githubusercontent.com/assets/12026068/10883367/745ab05c-81ac-11e5-93bd-58080185c0a9.jpg)

2. The velocity field within the rigid continental plate and the oceanic slab is disordered when I try to manifest horizontal movement of the plate (see animation, click to enlarge). The horizontal component `Vx` of the velocity extracted from on a passive tracer (I place them on the overriding continental block/plate) also shows strong oscillation.
![fig vx](https://cloud.githubusercontent.com/assets/12026068/10882831/e8fdc1f0-81a8-11e5-9e97-9418ae4d89d5.gif)
![fig vx](https://cloud.githubusercontent.com/assets/12026068/10883163/1d3e40f0-81ab-11e5-920d-71bb7f0a2f01.png)
Here is how it should looks like:
![fig vx2](https://cloud.githubusercontent.com/assets/12026068/10883247/9c15a2ce-81ab-11e5-9ea1-e1ef75c981e1.png)
Is this issue caused by insufficient grid resolution?

3. The stress tensor (read from `StressField.xxxxx.h5`, which should in fact refer to as the **deviatoric stress** tensor instead of the literal **stress** I guess) contains three components shown as StressField_X, StressField_Y, StressField_Z in Paraview, which are supposed to be the three independent variables `stress_xx`, `stress_yy`, `stress_xy` of the stress tensor. I'm a little bit confused: which is which?
![fig stresstensor](https://cloud.githubusercontent.com/assets/12026068/10882837/eecccac2-81a8-11e5-89d7-cfb480a9f866.jpg)

Thank you for your time!

Best,
Qingwen

**Comment by OlympusMonds** [comment]
1. The stress field, as far as I know, is generated from the equation: stress = 2 * viscosity * strainrate (although it's slightly more complicated in the _ConstitutiveMatrixCartesian2D_CalculateStress in Underworld/Rheology/src/ConstitutiveMatrix.c).
Therefore, I'm guessing that your stress field is spikey because your strain-rate is spikey. So have a look at the strain-rate. You may want to use "recovery" functions to make it smoother, but there are some issues with this.

2. This may be related to how "well" you solve your problem. What is the linear tolerance you're using? I typically use 1e-6, with a minimum of 10 iterations. If you're still having issues, try chaging the DtFactor to be smaller too. Furthermore, do you know what order your swarm advector is using? Try adding:
    ````<param name="timeIntegratorOrder"> 2 </param>````
to your input (near the elementResI, for example).

3. If you look in /Underworld/Utils/src/StressField.c, at about line 194, you can see that the 2D stress tensor is xx, yy, xy.

**Comment by QwZhang** [comment]
Hi all, sorry for my late reply. I think I get rid of the first two issues simplely by removing the "sticky air" layer and using higher resolution. Due to the exsit of this "sticky air", which bring in a hage contrast of the viscosity, high resolution and smaller time step is requred according to my test. After removing this layer, the modeling goes ahead far more fast and yields very stable velocity field. The disadvantage is that I can not simulate the free-surface on the top boundary with the help of this "sticky air" any more and there is only the free-slip one avaliable. 
So the key to solve this seems to use high resolution if one try to reserve "stick-air free-surface boundary condition. If so, much higher CPU time is required.

**Comment by jmansour** [comment]
Thanks for reporting back on this.  Possibly a more aggressive solver configuration might help.  The full free surface should also be possible soon (uw2), but that brings other potential difficulties.
