### ISSUE TITLE
TopFreesurface not working in parallel

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#268]
The thing is, in version underworld 2.2.2b 
I create the top Wall for boundary conditions

>>top  = mesh.specialSets["MaxJ_VertexSet"]

And then in the main loop, in order to have a top Free surface instead of sticky air I write:

>> with mesh.deform_mesh():
        mesh.data[top.data] += velocityField.evaluate(top) * dt
>> population_control.repopulate()

So this is working in jupyternotebook with one proccessor. 

**Problem: Same code is not working in parallel:**

TypeError: An exception was raised during mesh deformation. Your mesh may only be partially deformed. You can reset your mesh using the 'reset' method. Note that any submesh should not be modified directly, but will instead be updated automatically on return from the 'deform_mesh' context manager.

**Comment by jmansour** [comment]
Hi Angel

This is happening because in parallel, your index set `top` is empty on some processors (those which do not contain the top of the domain).  

As such, `velocityField.evaluate(top)` is returning `None`, and `None*dt` is then invalid.  A fix to get you through is to introduce a check to see if `top` is empty, and only perform the mesh deformation if it isn't. 

@julesghub, we should probably try and switch this to return an empty numpy array instead of returning a Python `None` object.  There are some difficulties however concerning the way functions operate.  I'll start a ticket. 

@AngelValverdePerez, try adding the check and report back for us.  Thanks.

**Comment by julesghub** [comment]
@jmansour yeah this is a gotcha between parallel and serial modelling. Best we identify other problem areas (in parallel it returns None) and fix the return values/API.
