### ISSUE TITLE
SafeMaths and exceptions

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#321]
For now when SafeMaths catches an underflow the model stops...but sometimes the result of an operation could effectively be flushed to zero. 
Could we add a bit of flexibility to the SafeMaths function so that a model does not stop when it catches a specific type of exception. Have it being flagged is still good...

**Comment by lmoresi** [comment]
Perhaps we need to reconsider “safe” … can you set a mode “warn” v. “terminate”

I like to think of the users in the notebooks. Termination leaves them with a kernel error and no warning messages. Far better to have some kind of warning and the solver return an error condition if trying to use values that are unsafe.

L

Prof Louis Moresi
louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>
(w)  +61 3 8344 1217
(m)  +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

On 12 Sep 2018 at 2:54 am, rbeucher <notifications@github.com> wrote:


For now when SafeMaths catches an underflow the model stops...but sometimes the result of an operation could effectively be flushed to zero.
Could we add a bit of flexibility to the SafeMaths function so that a model does not stop when it catches a specific type of exception. Have it being flagged is still good...

**Comment by jmansour** [comment]
`SafeMaths` doesn't kill the kernel so that must be something else Louis. We do aim to have all errors handled as exceptions (rather than destroy the kernel), but it's not always possible. Any kernel terminations that can be remedied (such as #319) should be reported as issues here.

Also, `SafeMaths` does its best to give a helpful message! I made some big improvements on this front recently (along with updates for usefully nesting `SafeMaths`).

A warning mode is a good idea. I would also like to implement a runtime `disable` option so you can remove it altogether (for the marginal performance gain) when you're confident in the numbers.
