### ISSUE TITLE
swarm space filler randomness 

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#33]
Repeated runs produce swarm layouts (when using space filler) which are visually quiet different. 

I believe this is an issue with the SobolGenerator.  Every new call iterates the SobolGeneratorGeneratorCount.  Perhaps this iteration is not necessary, but it would mean that the space filler produces identical results for identical input.

**Comment by jmansour** [comment]
643fda0f71d8d78b274aead99ff6c9cd8d1b3ecc

**Comment by lmoresi** [comment]
Good call, random is not a good way to distribute points if you want to fill space.

L


On 23 March 2016 at 10:06:45 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Closed #33<https://github.com/underworldcode/underworld2/issues/33>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/33#event-599516273>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
wasn't so much random (was still space filling), but the nature of the space filling changed every time you created a new swarm (or layout), and for later iterations the space filling becoming less homogenous (at the element scale).
