### ISSUE TITLE
Position of colorbar changes when changing figure quality.

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#341]
Hi @OKaluza 

I noticed that the position of the colorbar is changing when you change the quality from 1 to 3.
It overlaps the figure at quality=3.

**Comment by jmansour** [comment]
Yeah this is noticeable in #340 too.

**Comment by OKaluza** [comment]
Hi @rbeucher warning: long explanation incoming.

This has always been the case since the quality setting was added. The way it works is by rendering a larger image and downsampling it with bilinear filtering to get the output image.

- quality=1 : default font for colour bar labels is a bitmap font because it is readable without anti-aliasing and can be printed very small, this however looks blurry when it is scaled up and anti-aliased.
- quality > 1 : default font is a vector font that looks much better when drawn at larger sizes and anti-aliased, but if drawn at very small sizes without anti-aliasing is almost unreadable, so is less compact. 

The minimum size of the vector font is larger than that of the bitmap font, so the colourbar is pushed up slightly to make room for the labels. In general the vector font is much better looking but you just can't use it at small sizes without anti-aliasing.

To get it to look more consistent everywhere we would need to change the default margins and colourbar positioning, the reason I didn't do this when I introduced the anti-aliasing feature was it would change all the image outputs and require regenerating all test images etc so I left things as they were, also it was an experimental feature at the time.
I am happy to do this if you guys want me to, if I do so I would suggest making the default quality=2 or 3 and optimising the settings for nicer looking output.

The reasons quality=1 is the default:
- Faster to render (eg: quality=3 renders at [width*3 x height*3] so can be a little bit slower, depends on what is drawn)
- When the feature was first added experimentally, it had a bug or two and failed on some platforms, so leaving anti-aliasing off was deemed safer, as far as I'm aware it works fine on all platforms now, the test case that was failing in #340 uses quality=3 so wherever this test passes the feature is working.
