### ISSUE TITLE
MG solver 

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#345]
Hi all, I've been reading that MG solver is sometimes tricky, I have some doubts with using options in a proper way:

Is there any difference between: solver.set_mg_levels()  and solver.options.mg.set_levels()?

Also, I tried solver.set_mg_levels(8) due to high resolution and I get this error as @lmoresi wrote in other issue :  
(MG) Error: Too many levels specified for geometric multigrid.

Moreover, if I'm using a very high resolution for 2D model: 
mesh = uw.mesh.FeMesh_Cartesian( elementType = ("Q1/dQ0"),
                                 elementRes  = (1280, 448), ....)

which options are better to change for the MG solver to not consume a lot of memory?

**Comment by arijitlaik** [comment]
I guess the number of elements should be divisible by 2^(No_Of_MG_Levels) the yRes 448/256 is not a integer, 512 could help

**Comment by lmoresi** [comment]
1) No difference ... 

2) Your finest level for the mesh specified is 20 x 7 after dividing the mesh 7 times and that is as far as you can go. So that is why 8 levels breaks. Choose something that is divisible more times to as small a number as possible if you want more levels. 

3) The best thing is to try different strategies and see. These solvers are quite good and we are starting to get past the issue where there is simply no way to get the problem to converge (that is really quite something, by the way). 

There is quite a bit of discussion these days about squeezing 10 or 20% performance from the solvers but that is the kind of thing we would consider a "1st world problem"

L

**Comment by AngelValverdePerez** [comment]
That helps, thanks!
