### ISSUE TITLE
Suggestion: Move Integral to the function submodule...

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#348]
I am not a big fan of the utils submodule, I think the functions inside could be move elsewhere.
When we do calculation, it does not make sense to import `uw.function` and `uw.utils`..
What about moving Integral to the math or function submodule?

**Comment by lmoresi** [comment]
Agreed - the mix of things in utils is very eclectic. But this does not behave like a function, more like the projection operator and so they should probably be in a different place.

**Comment by jmansour** [comment]
Yeah, I think there's a fair amount of house keeping required across the entire project.  It is important because we're always pushing people to use autocomplete to explore the module, and with too much clutter it becomes much less useful. 

I've actually been meaning to move `Integral` to be a method of the `Function` class, `Function.integrate()`.  Something like this:
```python
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian()
meshvar = mesh.add_variable(1)
meshvar.data[:] = 3.
integ = meshvar.integrate(mesh)
```
But it does get a bit awkward for doing volumes
```python
one = uw.function.Function.convert(1.)
volume = one.integrate(mesh)
```

Actually, we do currently have integration directly hanging off the mesh object
```python
volume = mesh.integrate(1.)
```

I'm not sure what's better.  I'd rather have one way of doing things where reasonable.  I feel the integration is more a function _domain_ task, but the interface is perhaps cleaner via the mesh.  Either way, we could add automasking functionality for the spherical cases.

Also for projection, I think we should do

```python
othervar = mesh.add_variable(1)
uw.function.math.sqrt(meshvar).project_to(othervar)
```

And Louis has been calling on similar functionality for determining min/max
```python
# min/max over mesh
othervar.min_max(mesh)
# min/max over swarm
othervar.min_max(swarm)
```

**Comment by rbeucher** [comment]
Closing this... We just need to think of a better design in UW3
