### ISSUE TITLE
Value underflow/overflow

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#353]
Hi there! 

I'm running the same model in two different computers.

One is working with 2*2km of resolution with 1 node and 54 cores
in this pc is working fine...

Some model is running in an HPC with 0.8*1km of resolution with 4 nodes and 192 cores

In this one, when it runs few steps, at some point it gives this error:

Traceback (most recent call last):
  File "IberiaModel_1_2.py", line 3728, in <module>
    solver.solve(nonLinearIterate=True, nonLinearTolerance=0.08, nonLinearMaxIterations=30)
  File "/apps/UNDERWORLD/SRC/underworld2-2.5.1b/underworld/systems/_bsscr.py", line 413, in solve
    libUnderworld.StgFEM.SystemLinearEquations_MatrixSetup(self._stokesSLE._cself, None)
RuntimeError: Value underflow error was encountered while evaluating function.

So I was wondering what is causing this underflow error?

(sometimes I get an overflow error while evaluating the viscosity map)

Is due to resolution, number of particles, number of nodes? I'm trying to understand it. 

Any clue I'll appreciate it.

**Comment by julesghub** [comment]
Hi Angel,
What version of Underworld are you running?
Are you using SafeMaths to evaluate of the viscosity `function`?

**Comment by AngelValverdePerez** [comment]
Hi @julesghub 
using 2.5 version in both computers. 

And yes, I'm using: fn.exception.SafeMaths (fn.misc.max(powerLaw , plasticCriteria) )

**Comment by AngelValverdePerez** [comment]
Ok so I have done some test in the machine and the problem is not due to resolution or number of particles. The problem came up when using more than one node, so I do not know exactly how to fix architectural parallel issues.

**Comment by AngelValverdePerez** [comment]
I was going to say that I run some more few test and problem appear due to resolution problem, so I guess it's maybe related to resolution problem near the boundaries. 
And now with your comment, it has more sense. 
I will debug my code until I reach suitable boundary conditions with no very high viscosity contrast.

**Comment by AngelValverdePerez** [comment]
We can close this one, boundaries and high viscosity contrast always gives me some troubles and now I understand better what is overflaw or underflow error. 

Thanks!!! And Merry Christmas !!

**Comment by tingyang2004** [comment]
> Version 2.6 has some updates to the SafeMath model that may help. I recommend updating to that version if possible.
> 
> About the error.
> The value underflow represents an underworld function evaluating a value smaller than the cpu can represent, i.e. very very close to 0. Outside the floating point representation!
> 
> If you remove `SafeMaths` the code will not check for this warning and allow the very very small number to be used in the matrix. This should be ok as it's close to 0. BUT, removing `SafeMaths`, in general, can let in overflow issues which are catastrophic for solver convergence.
> 
> I assume this is happening in your `powerLaw` viscosity function.
> Try simplifying the function or clipping the input values to it, eg. strain rate invariant or temperature. Clipping the input values should put values in a valid floating-point range for the cpu arithmetic processor.

So underflow issue only appears when you put SafeMaths in your script if I understand it correctly?
If I set min_viscosity to truncate the minimum viscosity, can I remove SafeMaths?
viscosityFn = fn.exception.SafeMaths(fn.misc.max(fn.misc.min(viscosityNonBackgroundFn, backgroundViscosityFn), min_viscosity))

For my case it seems that the strain rate is so large that the viscosity gets extremely small. This issue does not appear in the stokes iteration, but it appears when I try to evaluate viscosity at the swarms. Any explanation for this? Thanks a lot.

**Comment by jmansour** [comment]
Note that `SafeMaths` doesn't modify any values, it simply reports when your values are problematic.  So whether a underflow occurs or not is independent of `SafeMaths` usage, but you will be made aware of it if using `SafeMaths` (and execution will be halted). 

It's a bit peculiar that you're only encountering the issue when evaluating on the swarm, but it's possible.  If it was consistently behaving like this, I'd suspect something was amiss.

**Comment by tingyang2004** [comment]
Thanks, John. Yes, I understand that SafeMaths only reports issues and does not modify the results.
The underflow issue does not occur often. Usually, when I conduct a few tens of models, some or none of them may experience the underflow issue after several hundred steps.  These models have the same model setup except that the value of a certain parameter is changed for each model.

Yes, it is very strange the underflow issue occurs in evaluating swarm viscosity in the post process but not in the stokes solver. Maybe I did not spot enough examples yet. Will keep an eye on that.

**Comment by tingyang2004** [comment]
The underflow issue occurs because I put evaluating swarm viscosities after advection. This explains why the underflow issue only occurs in the viscosity evaluation and why it occurs only occasionally.

In this sense,  the update part of 07_ShearBandsPureShear.ipynb needs to be modified. Although this specific example does not have the underflow issue, the example may be misleading.

**Comment by jmansour** [comment]
Can you explain further?  What is it an issue to evaluate the viscosities after the advection?

**Comment by tingyang2004** [comment]
The viscosity is calculated based on temperature, pressure, strain rate, yielding, composition, some spatial function and so on. Even if evaluating viscosity does not report any issues in the stokes solver, advect the swarm changes the conditions a bit and so evaluating the viscosity after advection may cause issues occasionally. Well, this is for my subduction case, which has very large viscosity contrasts within a short distance.

**Comment by tingyang2004** [comment]
By putting SafeMaths to different locations of the scipt, I was able to nail the issue to the following yielding viscosity evaluation:
yieldingViscosityFn =  fn.exception.SafeMaths(0.5 * yieldStressFn / (strainRate_2ndInvariant+SRMin))
where yieldStressFn is the yielding stress increasing with depth:
yieldStressFn   = frictionFn * rhom * fn.misc.max(0.0,zw-coord[1])+cohesionFn

However, since yieldStressFn is always positive (cohesionFn is a positive constant), strainRate_2ndInvariant+SRMin is also always positive. It is a bit difficult to figure out why swarm advection can get the underflow issue. 

![image](https://user-images.githubusercontent.com/26615840/76139543-e2cc9380-608b-11ea-8cae-20e9953cd1d6.png)

**Comment by lmoresi** [comment]
Missing particle after advection ?
On Mar 7, 2020, 6:59 PM +1100, tingyang2004 <notifications@github.com>, wrote:

By putting SafeMaths to different locations of the scipt, I was able to nail the issue to the following yielding viscosity evaluation:
yieldingViscosityFn = fn.exception.SafeMaths(0.5 * yieldStressFn / (strainRate_2ndInvariant+SRMin))
where yieldStressFn is the yielding stress increasing with depth:
yieldStressFn = frictionFn * rhom * fn.misc.max(0.0,zw-coord[1])+cohesionFn

However, since yieldStressFn is always positive (cohesionFn is a positive constant), strainRate_2ndInvariant+SRMin is also always positive. It is a bit difficult to figure out why swarm advection can get the underflow issue.

[image]<https://user-images.githubusercontent.com/26615840/76139543-e2cc9380-608b-11ea-8cae-20e9953cd1d6.png>

**Comment by tingyang2004** [comment]
Not sure how to verify this.
But evaluating the background viscosity does not report any underflow issue.
At least evaluating viscosity just after stokes solver and before swarm advection work for me now. So I will leave it here for now and may come back when the issue reappears or when there's some progress here. Many thanks, both.
