### ISSUE TITLE
compiling on NCI should be a test

### ISSUE THREAD

**Issue by mirkovelic** [underworldcode/underworld2#37]
I think our testing should include the code compiling on machines
like raijin etc.

Not much use if it only runs on laptops.

**Comment by jmansour** [comment]
I agree!!  @julesghub has been working on getting some more rigorous integration testing up and running (possibly using TravisCI).  To incorporate ~weekly build/run tests on machines such as magnus/raijin, I guess we'd have to write scripts to execute via ssh.  It would pull down the code there, load the required modules, configure, build, submit job to pbs.  It would also have to report success/otherwise at the various stages. 

Sounds like a script of doom like proportions! Think I know just the guy... 😀

**Comment by julesghub** [comment]
@mirkovelic next time you're at melbuni we can talk about this

**Comment by julesghub** [comment]
see #52 for more recent build instructions.

**Comment by julesghub** [comment]
We intent to test new releases on NCI and recommend modules for that release.
Closing ticket for now.
