### ISSUE TITLE
In Annulus models, TypeError occurs when evaluating velocity using array of points in parallel

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#389]
Hi,
In Annulus models, following exception occurs when velocityField.evaluate_global(pts) is used in parallel.
"""
An uncaught exception was encountered on processor 1.
Traceback (most recent call last):
  File "RotationTest_2D_NonLinear.py", line 295, in <module>
    print (np.sqrt(vc.evaluate_global(pts)[:,0]**2 + vc.evaluate_global(pts)[:,1]**2))
TypeError: 'NoneType' object is not subscriptable
application called MPI_Abort(comm=0x84000002, 1) - process 1
"""
Attaching script 
[RotationTest_2D_NonLinear_mod.txt](https://github.com/underworldcode/underworld2/files/3251557/RotationTest_2D_NonLinear_mod.txt)

Thanks.

thyagi

**Comment by jmansour** [comment]
Does this error occur on all processes?  I believe `evaluate_global` only returns results to proc 0, and other procs will be returned `None`, and `None[:,1]` would result in the message you're observing.  Try only run the `evaluate_global` on the root proc.

**Comment by gthyagi** [comment]
Hi @jmansour, 
I resolved the TypeError by running the evaluate_global on the root proc.
But program is not writing the evaluated values to a text in parallel. The script got stuck in the highlighted part. I am thinking that the issue is with file buffer. I am not sure how to resolve it.
"""
if uw.mpi.rank==0:
    pts = np.zeros((10, 2))
    pts[:,0] = np.random.rand(10,1)[:,0]
    pts[:,1] = np.random.rand(10,1)[:,0]
    vc_pf1 = vc.evaluate_global(pts)
    **outfile = open(outputPath+'time.txt', 'a')
    for i in vc_pf1:
        outfile.write("%.6e \t %.6e \n" %(i[0], i[1]))
    outfile.close()**
"""
Full Script [RotationTest_2D_NonLinear.txt](https://github.com/underworldcode/underworld2/files/3267722/RotationTest_2D_NonLinear.txt)

**Comment by jmansour** [comment]
`evaluate_global()` must be called collectively, which cannot occur in your snippet above because it is within the `if uw.mpi.rank==0` block.  You want something like this:

```python
pts = np.zeros((10, 2))
pts[:,0] = np.random.rand(10,1)[:,0]
pts[:,1] = np.random.rand(10,1)[:,0]
vc_pf1 = vc.evaluate_global(pts)
if uw.mpi.rank==0:
    **outfile = open(outputPath+'time.txt', 'a')
    for i in vc_pf1:
        outfile.write("%.6e \t %.6e \n" %(i[0], i[1]))
    outfile.close()**
```
Although check the details.

**Comment by lmoresi** [comment]
Occurs to me that some infrastructure might be useful here too. The use of random numpy arrays in parallel needs quite a bit of work to synchronise …

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 9 Jun 2019, 8:48 PM -0700, jmansour <notifications@github.com>, wrote:

evaluate_global() must be called collectively, which cannot occur in your snippet above because it is within the if uw.mpi.rank==0 block. You want something like this:

pts = np.zeros((10, 2))
pts[:,0] = np.random.rand(10,1)[:,0]
pts[:,1] = np.random.rand(10,1)[:,0]
vc_pf1 = vc.evaluate_global(pts)
if uw.mpi.rank==0:
    **outfile = open(outputPath+'time.txt', 'a')
    for i in vc_pf1:
        outfile.write("%.6e \t %.6e \n" %(i[0], i[1]))
    outfile.close()**

Although check the details.

**Comment by jmansour** [comment]
While I don't disagree, I'm not sure what this infrastructure should look like.

**Comment by jmansour** [comment]
I'm going to close this @gthyagi , but feel free to reopen if you are still having problems here.
