### ISSUE TITLE
Linking the geodynamic world builder to Underworld

### ISSUE THREAD

**Issue by MFraters** [underworldcode/underworld2#393]
Hello Underworld community,

I am the author of the Geodynamic World Builder (GWB in short, https://geodynamicworldbuilder.github.io/). It allows relatively easy construction of complex initial conditions (2d and 3d, cartesian and spherical).  During the review process of the paper (https://www.solid-earth-discuss.net/se-2019-24/, also see this for some nice pictures and the codes which it is already coupled to) one of the reviews suggested that there might be interest from the Underworld community to use the GWB. 

So I am wondering whether there are developers and/or user interested in this coupling. If there is interest, I am interested and willing to help coupling the two codes so that it becomes available to Underworld users.

If you need more information, or have question, please let me know!

Best,

Menno

**Comment by rbeucher** [comment]
Hi @Menno,

That looks like a nice project! I have developed UWGeodynamics https://github.com/underworldcode/UWGeodynamics which as already a lot of what you describe in GWB. I may be mistaken though. Happy to discuss that with you.

**Comment by jmansour** [comment]
Thanks for reaching out @MFraters.  

We're always interested in collaborations. As @rbeucher mentions, there's probably a bit of crossover between UWGeodynamics and GWB, but I don't think that's an issue. We all win when there's easy pathways between different community codes. @rbeucher you might even consider a JSON dump to cast UWGeo models into GWB format. 

As UW is a Python project, it probably makes sense to simply create a _weak_ coupling between UW and GWB.  It should be relatively straightforward to create a Python API from GWB's C/C++ API (using SWIG/Cython).  Then if

**Comment by rbeucher** [comment]
Yes, I have thought of doing a JSON dump as way to easily save setups. It works OK for simple models.

**Comment by MFraters** [comment]
> That looks like a nice project! I have developed UWGeodynamics https://github.com/underworldcode/UWGeodynamics which has already a lot of what you describe in GWB. I may be mistaken though. Happy to discuss that with you.

Thanks :) 

The movies on that site look really cool! I can see what you mean about the similarities, but I also see some differences. The UWGeodynamics is actually a geodynamics code which can solve the equations, while the GWB can only give initial conditions. The way to  parameterize initial conditions seems also different if I look at the examples (because different goals I guess). It will be interesting too see what would be the best way to get them talking somehow :)

> We're always interested in collaborations. 

Thanks for your interest! 

>As @rbeucher mentions, there's probably a bit of crossover between UWGeodynamics and GWB, but I don't think that's an issue. We all win when there's easy pathways between different community codes. @rbeucher you might even consider a JSON dump to cast UWGeo models into GWB format.

One of the goals of the GWB is that models created by one geodyanmics code can be run by another, so I hope we can make this work. 

> As UW is a Python project, it probably makes sense to simply create a weak coupling between UW and GWB. It should be relatively straightforward to create a Python API from GWB's C/C++ API (using SWIG/Cython). Then if the Python GWB can ingest `numpy` arrays of coordinates, and return physical values (viscosities/densities) or material types (reference indices perhaps), it's kinda job done. A Python GWB interface I think would also have wider usefulness in the community.

The GWB works in the following way. There is a function where you can ask: "what is the temperature at this position?" and there is a function which can ask: "What is at this position the value of composition with index i?" where i is an integer. The composition function returns a double where 0 means not present, and 1 means 100% is that composition. For these c++ functions I currently have c and fortran wrappers. I agree that adding python wrappers should not be difficult, but it is good to know what specifications it needs (like that it needs to be able to import a `numpy` array.

**Comment by lmoresi** [comment]
I am generally in favour of leveraging whatever other codes we can to do things that we find hard to maintain. The idea of the world-builder is very attractive in principle.

As Romain pointed out, there is overlap at the moment but that may be helpful in breaking down where each group should devote their efforts. Python wrappers ought to be helpful in this regard.

Let’s keep this conversation going.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 13 Jun 2019, 2:50 AM +0100, MFraters <notifications@github.com>, wrote:

That looks like a nice project! I have developed UWGeodynamics https://github.com/underworldcode/UWGeodynamics which has already a lot of what you describe in GWB. I may be mistaken though. Happy to discuss that with you.

Thanks :)

The movies on that site look really cool! I can see what you mean about the similarities, but I also see some differences. The UWGeodynamics is actually a geodynamics code which can solve the equations, while the GWB can only give initial conditions. The way to parameterize initial conditions seems also different if I look at the examples (because different goals I guess). It will be interesting too see what would be the best way to get them talking somehow :)

We're always interested in collaborations.

Thanks for your interest!

As @rbeucher<https://github.com/rbeucher> mentions, there's probably a bit of crossover between UWGeodynamics and GWB, but I don't think that's an issue. We all win when there's easy pathways between different community codes. @rbeucher<https://github.com/rbeucher> you might even consider a JSON dump to cast UWGeo models into GWB format.

One of the goals of the GWB is that models created by one geodyanmics code can be run by another, so I hope we can make this work.

As UW is a Python project, it probably makes sense to simply create a weak coupling between UW and GWB. It should be relatively straightforward to create a Python API from GWB's C/C++ API (using SWIG/Cython). Then if the Python GWB can ingest numpy arrays of coordinates, and return physical values (viscosities/densities) or material types (reference indices perhaps), it's kinda job done. A Python GWB interface I think would also have wider usefulness in the community.

The GWB works in the following way. There is a function where you can ask: "what is the temperature at this position?" and there is a function which can ask: "What is at this position the value of composition with index i?" where i is an integer. The composition function returns a double where 0 means not present, and 1 means 100% is that composition. For these c++ functions I currently have c and fortran wrappers. I agree that adding python wrappers should not be difficult, but it is good to know what specifications it needs (like that it needs to be able to import a numpy array.

**Comment by MFraters** [comment]
It took me a while to get to it, and it was a bit more difficult than I expected but I now have a draft version of the python wrapper at https://github.com/GeodynamicWorldBuilder/WorldBuilder/pull/144. 

Since you all have a lot more experience with python then I have, can I also for someone there to take a look at it to see 1) if it what is needed to link underworld 2 to the world builder and 2) if there are any python problems or conventions I might have missed in the implementation?

Thanks!
