### ISSUE TITLE
Imposed velocity boundary condition with a threshold

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#399]
Hi all,

I am thinking of imposing a velocity to a point within the strong lithosphere to module the plate motion. The prescribed velocity must be always larger than a threshold. That is, if the stokes solver derived velocity is larger than the threshold at this point, the stokes flow velocity is used. But if the stokes solver derived velocity is smaller than the threshold, the threshold value is used. Any suggestions? Thanks a lot.

Best regards,
Ting

**Comment by jmansour** [comment]
There's only two possible outcomes:

a) Solution without prescribed velocity at point. 
b) Solution with prescribed velocity at point. 

Therefore, solve system (a), and if the velocity is greater than the threshold, that solution becomes the retained solution for that timestep.  Otherwise, solve (b), and use that solution.

**Comment by tingyang2004** [comment]
Thanks a lot John.
So you have two stokes solvers. One the default one without the prescribed velo. You solve it in each step and once the derived velo at the point is less than the threshold, you start up the backup vetsion. Is that right? Is there anything I need to be care of in parallel?

**Comment by lmoresi** [comment]
Depends on whether the problem has non-linearities though — it would be advisable to iterate …

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 10 Jul 2019, 3:16 AM -0700, jmansour <notifications@github.com>, wrote:

There's only two possible outcomes:

a) Solution without prescribed velocity at point.
b) Solution with prescribed velocity at point.

Therefore, solve system (a), and if the velocity is greater than the threshold, that solution becomes the retained solution for that timestep. Otherwise, solve (b), and use that solution.

**Comment by jmansour** [comment]
@lmoresi does it though?  Yes, you may need to iterate in either case (a) or case (b) if there are non-linearities, but both problems are independent of each other. That is assuming uniqueness of solutions. I believe. 

@tingyang2004, yes what you are saying sounds correct.  There are parallel considerations, specifically that the point in question will only exist on one process. You can use the `evaluate_global()` method to determine the value at the required point, but you will also need to communicate the required result to all procs, so that they all know when they need to switch to the backup.  There are a few ways you can go about it, but I think simply using `mpi4py` would be most transparent.  Have a go, and keep us posted here.

**Comment by tingyang2004** [comment]
Since the non-linear solver usually takes two to three iterations and it is only in a short period of model's evolution that I need to switch to the backup, I would just take John's scheme now. @lmoresi 
mpi4py sounds a good choice, will let you know how it goes. @jmansour 
BTW, can I put the two stokes solvers in a function so I invoke either solver based on the parameter passed to the function?
e.g.,
def SolveStokes (SOLVERPV):

    if SOLVERPV == 1:
        for index in InnerVeloNodesB:
            velocityField.data[index][0] = InnerVeloBCVx0B
        solverPV.solve(nonLinearIterate=True,nonLinearMaxIterations=200,nonLinearTolerance=0.003)
        solverPV.print_stats()
    else:
        solver.solve(nonLinearIterate=True,nonLinearMaxIterations=200,nonLinearTolerance=0.003)
        solver.print_stats()
    return

and in the while loop I invoke it as below:
    if SOLVERPV == 0 and time > 1./tao: # larger than 1 Myr
        SPVel=velocityField[0].evaluate_global([InnerVeloBCXB,zwCont-50e3/h])
        SPVel=comm.bcast(gridt[1,:],root=0)
        comm.barrier()
        if SPVel[0]<InnerVeloBCVx0B:
            SOLVERPV = 1
            timePV  = time
    if SOLVERPV == 1 and time > timePV+10./tao:
        SOLVERPV = 2
    SolveStokes(SOLVERPV)

**Comment by tingyang2004** [comment]
Not sure what was wrong. It looks like I cannot put the two stokes solver in one python script? Once I remove the comments before stokesPV, the stokes solver always has a convergence issue during the non-linear iteration. Do you have any suggestions? Thanks.


-stokesPV = uw.systems.Stokes(    velocityField = velocityField,
-                               pressureField = pressureField,
-                               #voronoi_swarm = swarm, 
-                               conditions    = VelBCPV,
-                               fn_viscosity  = viscosityFn,
-                               fn_bodyforce  = buoyancyFn )
+#stokesPV = uw.systems.Stokes(    velocityField = velocityField,
+#                               pressureField = pressureField,
+#                               #voronoi_swarm = swarm, 
+#                               conditions    = VelBCPV,
+#                               fn_viscosity  = viscosityFn,
+#                               fn_bodyforce  = buoyancyFn )
 # Create solver & solve
-solverPV = uw.systems.Solver(stokesPV)
+#solverPV = uw.systems.Solver(stokesPV)

**Comment by jmansour** [comment]
🤔

I'm not 100%.  It's possible that because the same velocity `MeshVariable` is used for both systems, something is tripping up here.

Can you try again, but instead create two velocity fields and two pressure fields.  One of each for each system.  Then solve.  You will need to copy the final vel/pressure after each solve then so that the correct one is used for the particle advection and/or temp advection diffusion. 

If you post a small example, I can take a closer look.

**Comment by tingyang2004** [comment]
I have just tried a model with only the linear viscosity and the model runs without an issue. Will create two velocity and pressure fields as you suggested.

**Comment by tingyang2004** [comment]
Seems a bit complex, the strain rate depends on velocity, the viscosity (dislocation and yielding) depends on the strain rate, so a lot of quantities need to have two versions.

**Comment by lmoresi** [comment]
John et al,

This is why, ultimately, the equation system ought to be able to define its internal variables in the first instance. It is clear that coupling systems will require there to be
variables defined externally, but for this kind of problem, it is clunky to use the original set up.

And a question to @rbeucher … would UWGeodynamics handle the 2 solver case “correctly” or is that assumption that there is only one Stokes solver built in.

L

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 11 Jul 2019, 2:46 AM -0700, tingyang2004 <notifications@github.com>, wrote:

Seems a bit complex, the strain rate depends on velocity, the viscosity (dislocation and yielding) depends on the strain rate, so a lot of quantities need to have two versions.

**Comment by rbeucher** [comment]
@lmoresi my idea of a Model class was to encapsulate everything so that I could have several of them that could be coupled or embedded within each other like Russian dolls. In my case each solver has its own mesh variables. I still need to test a lot of things. I also wanted to clean that monster class before doing any more.

**Comment by rbeucher** [comment]
But for one Model class the assumptuon is that
There is one solver only...

**Comment by jmansour** [comment]
@rbeucher  UWGeodynamics - The Babushka edition. 

@lmoresi, I'm not really following how the alternative is better in this case. If anything, it seems like having the variables initially defined externally here makes more sense. Perhaps I'm not understanding what you mean.

I've attached a model which seems to work as expected. Take a look @tingyang2004 .

[dual_system.tar.gz](https://github.com/underworldcode/underworld2/files/3384499/dual_system.tar.gz)

**Comment by rbeucher** [comment]
The Hunt for Red October edition!

**Comment by tingyang2004** [comment]
Alternating between two solver systems works fine for me now if I create two velocities, pressure and thus strain rate, and viscosity. 

As a summary, for linear stokes solver, no need to duplicate these quantities, but for non-linear stokes solver, a duplication of variables (annoying) solves the issue.

**Comment by tingyang2004** [comment]
Just saw your example, looks like you do not need to double the variables? @jmansour

**Comment by tingyang2004** [comment]
Strange, John's example converges very fast, the non-linear solver converges after 7 iterations.
![image](https://user-images.githubusercontent.com/26615840/61098775-b88dec00-a492-11e9-8a0b-cdeaa46e0cb0.png)

but when I change the viscosity formula from
visc = 1. + fn.math.abs(vel[0])
to
visc = 1. + fn.math.abs(vel[0]),
that is, the viscosity has a larger dependence on velocity,
the non-linear solver did not converge and the iteration number reaches the limit of 500:
![image](https://user-images.githubusercontent.com/26615840/61098805-cd6a7f80-a492-11e9-9c55-e9c83f3cf9d8.png)

**Comment by jmansour** [comment]
The iteration count to convergence will certainly depend on the strength of
the non linearity.

**Comment by jmansour** [comment]
Here's a binder via a github gist:

https://mybinder.org/v2/gist/jmansour/7ecc3d80b4b2056ad5c4a5ab0ebf08f6/master?filepath=dual_system.ipynb

MyBinder can also launch directly off Zenodo DOIs:
https://mybinder.org/v2/zenodo/10.5281/zenodo.1436039/
