### ISSUE TITLE
gLucifer operator bug

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#40]
The gLucifer examples have this code:

```python
figtemp = glucifer.Figure( figsize=(800,400) )
figtemp + glucifer.objects.Surface( mesh, temperatureField, colours="blue white red" )
figtemp + glucifer.objects.Mesh( mesh )
figtemp.show()
```

I'm not sure what this means so I tried this

```` python
figtemp = glucifer.Figure( figsize=(800,400) )
figtemp1 = figtemp + glucifer.objects.Surface( mesh, temperatureField, colours="blue white red" )
figtemp2 = figtemp + glucifer.objects.Mesh( mesh )
figtemp2.show()
````

I get identical images for any of

````python
figtemp.show()
figtemp1.show()
figtemp2.show()
````

It is as though the + operator is behaving like += in C. 

This seems broken. I would expect these to be equivalent

``` python
figtemp += glucifer.objects ... 
figtemp = figtemp + glucifer.objects ...
```

**Comment by lmoresi** [comment]
(I guess this is actually a Mansour issue )

**Comment by jmansour** [comment]
I understand what you're saying Louis, but this isn't actually an overload for object addition. We can't add objects of different type!

It's really syntactic sugar for an `add_object` type method. I went this way because I thought it would aid readability, but happy to get rid of it if people find it more confusing than useful.  

These are our options:

current:
```
figtemp + glucifer.objects.Surface( mesh, temperatureField, colours="blue white red" )
```
alternative:
```
figtemp1.add_object( glucifer.objects.Surface( mesh, temperatureField, colours="blue white red" ) )
```

**Comment by lmoresi** [comment]
Let the people speak ...

Just seems different from standard Python syntax. Also a good opportunity to give you some grief. Never a bad thing in the holiday season. Happy Christmas !

Sent from my iPhone

On 13 Dec 2015, at 19:43, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


I understand what you're saying Louis, but this isn't actually an overload for object addition. We can't add objects of different type!

It's really syntactic sugar for an add_object type method. I went this way because I thought it would aid readability, but happy to get rid of it if people find it more confusing than useful.

These are our options:

current:

figtemp + glucifer.objects.Surface( mesh, temperatureField, colours="blue white red" )


alternative:

figtemp1.add_object( glucifer.objects.Surface( mesh, temperatureField, colours="blue white red" ) )

**Comment by jmansour** [comment]
I've countered your grief giving via the consumption of ginger bread!

**Comment by jmansour** [comment]
Yeah, it isn't standard...  possibly isn't even pythonic(!), which perhaps should rule it out immediately. I guess once you know what it does, the current is visually easier, but with the alternative, you don't need to consult the documentation to be pretty confident of what it actions.

**Comment by lmoresi** [comment]
Let's see what the others say !

Sent from my iPhone

On 13 Dec 2015, at 19:56, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, it isn't standard... possibly isn't even pythonic(!), which perhaps should rule it out immediately. I guess once you know what it does, the current is visually easier, but with the alternative, you don't need to consult the documentation to be pretty confident of what it actions.

**Comment by mirkovelic** [comment]
What about

fig.append('blah') ?

I shall return to the hookah to ponder.

**Comment by julesghub** [comment]
Yeah the quasi-sugar operator overloading is confusing because one could
think the data structures are the same type, but they are NOT.
My vote is for the function style, less fancy but more obvious under the
hood. I like the append() name because it hints that you're dealing with a
list data structure - which the draw objects are stored as right?

J

**Comment by OKaluza** [comment]
How about we just use a public member variable as the object list?

We could forget providing a special interface to the list of objects and
let the user manage it python list style... with either append() etc or
operators...

figtemp = glucifer.Figure( figsize=(800,400) )

surf = glucifer.objects.Surface( mesh, temperatureField, colours="blue
white red" )

figtemp.objects = [surf]
figtemp.objects += [glucifer.objects.Mesh( mesh )]
figtemp.objects.append(glucifer.objects.Vectors(...))

figtemp.show()

On 14 December 2015 at 09:32, julesghub <notifications@github.com> wrote:

> Yeah the quasi-sugar operator overloading is confusing because one could
> think the data structures are the same type, but they are NOT.
> My vote is for the function style, less fancy but more obvious under the
> hood. I like the append() name because it hints that you're dealing with a
> list data structure - which the draw objects are stored as right?
>
> J
>
> On 13 December 2015 at 22:28, Mirko <notifications@github.com> wrote:
>
> > What about
> >
> > fig.append('blah') ?
> >
> > I shall return to the hookah to ponder.
> >
> >
> > On Sun, Dec 13, 2015 at 10:18 PM, Louis Moresi <notifications@github.com
> >
> > wrote:
> >
> > > Let's see what the others say !
> > >
> > > Sent from my iPhone
> > >
> > > On 13 Dec 2015, at 19:56, jmansour <notifications@github.com<mailto:
> > > notifications@github.com>> wrote:
> > >
> > >
> > > Yeah, it isn't standard... possibly isn't even pythonic(!), which
> perhaps
> > > should rule it out immediately. I guess once you know what it does, the
> > > current is visually easier, but with the alternative, you don't need to
> > > consult the documentation to be pretty confident of what it actions.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub<
> > >
> >
> https://github.com/underworldcode/underworld2/issues/40#issuecomment-164240491
> > > >.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/underworldcode/underworld2/issues/40#issuecomment-164247899
> > >
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/underworldcode/underworld2/issues/40#issuecomment-164248595
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/underworldcode/underworld2/issues/40#issuecomment-164306600>
> .
>



-- 
Owen Kaluza <owen.kaluza@monash.edu>
Senior Visualisation Specialist, eResearch Support
Monash University, Clayton Campus, Rm.318, Building 82
Phone: 03 9902 9809, Mobile: 0410 545 824

**Comment by OlympusMonds** [comment]
I would vote for choosing to be like matplotlib. Since the numpy objects are so easily accessible, and to do any sort of plotting (line, bar, whatever other MPL plugins exist) you need MPL anyway. Furthermore, MPL plotting is being used in the UW2 tutorials already.
I do agree with John that the MPL style is not super intuitive, and the + format is more so; but for newbies starting out, it is now 2 new things to learn (MPL plotting and lavavu plotting), rather than just MPL. For the more experienced, MPL is relatively well known, so it would be nice to be able to use the same format. 
The problem with doing MPL style is that it generates an expectation of functionality - it would be strange to have MPL style, and then find out that plt.xlim() doesn't work on a lavavu figure.
Anyway, just my 2c!

**Comment by OKaluza** [comment]
I'm happy to have it simulating MPL where it makes sense but I'm not super familiar with the MPL interface.
As you say Luke the trouble with using the same format as MPL is the confusion caused by the false equivalence (ie: Matplot lib plots have axes with arbitrary variables assigned, LavaVu is a 3D renderer where axes are always XYZ spatial coords but it can be hacked to do 2D plots by using cross-sections).
I think this is potentially a bigger problem than having to learn a different style of API. To use any of the power of LavaVu you are going to have to use different commands anyway so in some ways it's better to realise they are different early on, except for the obvious parallels, like rendering a plot or saving an image, etc.
That said, I don't have to change LavaVu to implement another API of course, it can all be done in the python layer, just be aware the more complex the wrapper layer to simulate MPL is, the higher the maintenance burden and number of points of breakage as compared to calling LavaVu functions or script commands directly. Of course this will matter less when we have some automated tests up and running again.

**Comment by jmansour** [comment]
So the original python interface implementation was designed to be as close to matplotlib as possible.  As the python interface has progressed, it has moved away from the mpl style interface due to necessity (differences in functionality as owen discusses), and also due to dissatisfaction with certain aspects of the mpl design. That said, there is still a fair bit of mpl style in the current interface, and I agree with Luke that it's good to provide something familiar where reasonable. 

In fact, the main thing I wasn't happy with about the mpl interface is the very detail we're discussing here.  

Previously we had something like 
```python
fig = plt.Figure()
fig.Points( swarm=swarm, etc) 
```
which while concise, isn't particular great (coupling across modules, code repetition), and also didn't play as nice with autocomplete suggestions as the current implementation.

**Comment by jmansour** [comment]
Owen, the public member isn't a bad option.  I guess it would be nice to have incompatible types caught out immediately, but it's probably not a huge drama to catch them at `fig.show()` (/etc) time.  

Alternatively we could derive from the python list class, and add the check to our own 'append' method:

```python
class LucList(list):
    define append(self, object):
        if not isinstance(object, objects.DrawingObject):
            raise TypeError("naughty naughty")
    super(LucList,self).append(object)
```

Perhaps overkill... also not sure if we'd need to override other similar methods (`extend`, `insert`, etc).

**Comment by OKaluza** [comment]
The only time the list is iterated is in Figure.generate_DB() so it would be easy to just do the check here and skip any invalid items (or throw an error if preferred)

**Comment by lmoresi** [comment]
I've commented before that, in 2d, the natural interface with matplotlib would be to generate images with an associated extent and allow people to layer these into graphs / insets etc.

Then it would be plausible to make lavavu less matplotlib like but have a store_image function to grab the rendered image.

It's less obvious that one would want to do this with 3D but matplotlib is ugly and clunky in 3D.

I'm not a fan of matplotlib and its interface. That is partly why I like the idea of introducing a demilitarised zone between it and lavavu in the glucifer interface.

Sent from my iPhone

On 13 Dec 2015, at 21:08, Luke Mondy <notifications@github.com<mailto:notifications@github.com>> wrote:


I would vote for choosing to be like matplotlib. Since the numpy objects are so easily accessible, and to do any sort of plotting (line, bar, whatever other MPL plugins exist) you need MPL anyway. Furthermore, MPL plotting is being used in the UW2 tutorials already.
I do agree with John that the MPL style is not super intuitive, and the + format is more so; but for newbies starting out, it is now 2 new things to learn (MPL plotting and lavavu plotting), rather than just MPL. For the more experienced, MPL is relatively well known, so it would be nice to be able to use the same format.
The problem with doing MPL style is that it generates an expectation of functionality - it would be strange to have MPL style, and then find out that plt.xlim() doesn't work on a lavavu figure.
Anyway, just my 2c!

**Comment by lmoresi** [comment]
Agreed John.

Matplotlib is a dogs breakfast trying to keep too many matlab users happy.

Sent from my iPhone

On 13 Dec 2015, at 22:34, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


So the original python interface implementation was designed to be as close to matplotlib as possible. As the python interface has progressed, it has moved away from the mpl style interface due to necessity (differences in functionality as owen discusses), and also due to dissatisfaction with certain aspects of the mpl design. That said, there is still a fair bit of mpl style in the current interface, and I agree with Luke that it's good to provide something familiar where reasonable.

In fact, the main thing I wasn't happy with about the mpl interface is the very detail we're discussing here.

Previously we had something like

fig = plt.Figure()
fig.Points( swarm=swarm, etc)

which while concise, isn't particular great (coupling across modules, code repetition), and also didn't play as nice with autocomplete suggestions as the current implementation.
