### ISSUE TITLE
How to get the columnwise Swarm variable data in a particular mesh

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#442]
Hi All,

I have a mesh and a swarm developed with the particular mesh. Also there is a swarm variable called 'Mext'.

I want to divide the this mesh into columns and want to find the sum of Mext.data values within the particular columns and store them in a list.

Could you please suggest a fast method to do this in UW2 without many for loops?

Thank you
Pras

**Comment by jmansour** [comment]
You could use `np.where()` to get the list of particles within any given column (assuming the columns are axis-aligned), and then perform the sum. But in parallel you will then need to sum contributions from each process, possibly using `mpi4py`.

Alternatively you could use an underworld integral, and construct the integral of `Mext*columnfunc` where `columnfunc` is a function describing the required column (ie, equal to `1.` inside the column, and `0.` otherwise).  You could either do an integral of a vector of `columnfunc` functions describing your list of columns, or have a separate integral for each column.  The former will probably be faster, though the difference shouldn't be huge.

**Comment by Prasanna2989** [comment]
In the first method how should I select all the particles indexes where (coord[0] > some value), and (coord[1] <some value)?

**Comment by Prasanna2989** [comment]
Got the answer. Thanks
