### ISSUE TITLE
A bug of evaluate() method?

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#445]
Hi, Underworld2 developers:
I define a simple function to calculate the pressure. However, I get the wrong results after evaluating it on the whole mesh that has minimum vertical coordinate of -1 and maximum of 1. 
Here are my codes of the mesh and function: 
![image](https://user-images.githubusercontent.com/50648269/70763707-fff50d00-1d8f-11ea-85d1-23539726623c.png)
![image](https://user-images.githubusercontent.com/50648269/70763717-0aafa200-1d90-11ea-9868-6bfa6b6c6695.png)
The results are incorrect. Then I change another form of my codes and evaluate them on the same mesh, and it gives me different wrong results. 
Different codes and results of the function:
![image](https://user-images.githubusercontent.com/50648269/70764258-fbc9ef00-1d91-11ea-8051-a97f0bb9d4de.png)
It seems to be a bug of evaluate() method. I want to make out the reason. Hope to receive your reply.
Thanks for your help.

**Comment by jmansour** [comment]
You're confusing Underworld `Function` objects with Python functions.  The two are not interchangeable.  

In both your snippets, you are using `coo[1]>=0` and `coo[1]<0`, however both of these statements evaluate to an Underworld `Function` object (due to operator overloading). Now, in Python, `if something` always evaluates to `True` if `something` is not equal to `0`, `False` or `None`.  Therefore in the first version, you always return the first `pressure_field`, and in the second version you always return the second `pressure_field`.

I think you probably want to use the `underworld.function.branching.conditional()` class.  Something like this:
```python
import underworld as uw
import underworld.function as fn
mesh = uw.mesh.FeMesh_Cartesian()

coo = fn.input()
pressure_field = fn.branching.conditional(  ( 
                                         (coo[1]>=0.5, 8.*coo[1]), 
                                         (coo[1]<0.5,  -3000.*coo[1])  )  )
pressure_field.evaluate(mesh) 
```

**Comment by jmansour** [comment]
https://underworld2.readthedocs.io/en/latest/build/underworld.function.branching.html#underworld.function.branching.conditional
https://underworld2.readthedocs.io/en/latest/build/user_guide/04_Functions.html

**Comment by alexstruc** [comment]
Ok, I get it. Thank you.

**Comment by jmansour** [comment]
No probs.
