### ISSUE TITLE
how to deal with surface process?

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#450]
Hi, all:
I am trying to model the evolution of collision orogens and I think the surface erosion and sedimentation could affect the results. I find the transport equations from Gerya(2010).
![4c3c3fe1dee4f93312ee52118dae9c6](https://user-images.githubusercontent.com/50648269/72214614-de2ea780-3540-11ea-8f28-faed6a22c89f.png)
![a78c8af3dfcd16fabda93fc07613651](https://user-images.githubusercontent.com/50648269/72214616-e1299800-3540-11ea-993c-c2b819535767.png)
The second one is for short-distance,downhill diffusion erosion.
But I don't know how to put them into my models. Are there any suggestions or relevant examples.
Best Regrades!
Alex.

**Comment by rbeucher** [comment]
We use Badlands in general. underworldcode/uwgeodynamics has a module that allows Badlands to interact with Underworld.

It might be overkill sometimes...

I have been thinking of implementing something simpler, like the equations you suggested, but never finished it. It depends on how you define your top surface. It is relatively simple with a free surface. With sticky air you first need to track the interface... Then it's basically a diffusion problem.

It's relatively trivial in serial. It's a bit more complicated in parallel which is why I have not finished the code. @arijitlaik has done something interesting.

I don't have plans to work on that for now but feel free to contribute!!

**Comment by alexstruc** [comment]
Thanks for your response. I know little about Badlands now, but I will try to implement it into my model next.
