### ISSUE TITLE
Where is the 'inner' solver applied?

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#473]
Hi all,

It looks like user_guide has only a brief introduction to solving the Stokes equations in UW2, and after reading it, I am still confused about how velocity and pressure are derived. Here are some questions:

It looks like p is solved first with Sp=h_hat, and then velocity is solved with K*u=f-G*p? 
Since S incorporates the inverse of the stiffness matrix K, how is it set in UW2 to bypass inv(K)? 
And how is the velocity solved with pressure known? 

It would be great if you can recommend some documents or material giving a more detailed description of these things? Thanks a lot.

Best regards,
Ting

**Comment by julesghub** [comment]
Hi Ting, an excellent document on this https://doi.org/10.1016/j.pepi.2008.07.036

Section 2.2 is what you're after. 
It outlines the "inner" solve which approximates the action of inv(K) rather than explicitly forming inv(K). This corresponds to the `A11` options in UW2. 
The resultant approx of inv(K) is used in the "outer" solve, which is the Sp=h_hat, ie. the `scr` options in UW2.

Once pressure is solved ("outer" solve residual error is small enough) a backsolve is made ( using equation 23. in the above document) to solve for velocity.

I'll close this ticket for now but feel free to reopen if you have questions.

**Comment by tingyang2004** [comment]
Thanks so much, Julian. Very helpful documents and information. @julesghub
