### ISSUE TITLE
is fn_stresshistory in the stokes solver the advected history stresss?

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#486]
Hi all,

I am a bit confused about the smoothing strategy applied to the historical stress in the 11_ViscoelasticityInSimpleShear viscoelastic rheology example:
```
    # smoothed stress history for use in (t + 1) timestep   
    phi = dt / dt_e;
    stressMapFn_data = stressMapFn.evaluate(swarm)
    previousStress.data[:] = ( phi*stressMapFn_data[:] + ( 1.-phi )*previousStress.data[:] )

```
Does this mean that the smoothed stress is the advected and rotated historical stress and acts directly as an extra force term in the stokes solver? In this case, is there any proof the advected stress can be represented this way?

Or maybe fn_stresshistory provided to the stokes solver is the original historical stress and its advection and rotation process is done in the hidden layer of UW2? In this case, why is the smoothing strategy needed? Thanks a lot in advance for your suggestions and comments.

Best regards,
Ting

**Comment by tingyang2004** [comment]
Thanks, Rebecca.

Glad to hear from you too!

So advection of the historical stress is done through smoothing historical stress in the past few steps? 
I am also wondering why you choose 1/3 the elastic time as your step interval since this makes the solver 3 times more expensive.

I will have a closer check of the tutorials and paper later.

Best regards,
Ting

**Comment by lmoresi** [comment]
Ting,


The smoothing is perhaps better viewed as a mechanism for obtaining a running average value of the historical stress over the chosen elastic timestep. If this is not done, then the choice of timestep becomes limited by the shortest relaxation time in the model - that can be very much shorter than the time that is necessary in the regions where elastic stresses are largest (e.g. the lithosphere). If you take a larger timestep, the averaging should keep the problem stable but you will not resolve the stress history correctly but there is a stability criterion that required us to average over at least three steps.

This approach was motivated by minimising the number of stored copies of the stress tensor. I suspect that modern architectures might make it more reasonable to have higher order stress updates and this scheme could then be dropped. You might want to try that - the stress history is explicitly stored in UW and could be modified however you want and re-inserted into the RHS.

Rebecca can answer in detail where I might have glossed over something.

L
On 11 Jun 2020, 11:47 AM +1000, tingyang2004 <notifications@github.com>, wrote:

Thanks, Rebecca.

Glad to hear from you too!

So advection of the historical stress is done through smoothing historical stress in the past few steps?
I am also wondering why you choose 1/3 the elastic time as your step interval since this makes the solver 3 times more expensive.

I will have a closer check of the tutorials and paper later.

Best regards,
Ting

**Comment by tingyang2004** [comment]
Hi Louis,

Thanks a lot. Very helpful!
That explains why I got very similar results when I commented out the smoothing part of the code in the viscoelastic simple shear model. The simple shear model has only one material and thus no large contrasts of the relaxation time between different materials. I will make a further test of this later with more models.

Yes, will be interested in the 'higher order stress updates'.

Best regards,
Ting

**Comment by julesghub** [comment]
Thanks for the discussion all. We are moving this to a (Jira ticket) UW2-455.
Closing the ticket for now, feel free to reopen if you have other questions @tingyang2004.

**Comment by tingyang2004** [comment]
Thanks for closing it, Julian. I don't have any questions right now.

**Comment by RebeccaFarrington** [comment]
Happy to discuss further if/when needed.
Cheers,

**Comment by ythaha** [comment]
Sorry to bother you. I am still confused on the smoothing method. Especially why this smoothing will _accounts correctly for rotation_. The picture is taken from Moresi 2002 https://hal.archives-ouvertes.fr/hal-01620839/document

and why in Underworld we do not calculate W (rotation)  explicitly to account for rotation?

Thanks!

![image](https://user-images.githubusercontent.com/22343435/139530428-4aa9c74f-6636-485b-848d-18393878fc7b.png)

**Comment by ythaha** [comment]
In Aspect, they calculate the rotation term `symmetrize(rotation * Tensor<2,dim>(stress_old) ) - symmetrize(Tensor<2,dim>(stress_old) * rotation) )`
```cpp
    // Calculate the rotated stresses
    // Rotation (vorticity) tensor (equation 25 in Moresi et al., 2003, J. Comp. Phys.)
    const Tensor<2,dim> rotation = 0.5 * ( old_velocity_gradients[i] - transpose(old_velocity_gradients[i]) );

    // Average viscoelastic viscosity
    const double average_viscoelastic_viscosity = out.viscosities[i];

    // Calculate the current (new) viscoelastic stress, which is a function of the material
    // properties (viscoelastic viscosity, shear modulus), elastic time step size, strain rate,
    // vorticity and prior (inherited) viscoelastic stresses (see equation 29 in Moresi et al.,
    // 2003, J. Comp. Phys.)
    SymmetricTensor<2,dim> stress_new = ( 2. * average_viscoelastic_viscosity * deviator(in.strain_rate[i]) ) +
                                        ( ( average_viscoelastic_viscosity / ( average_elastic_shear_moduli[i] * dte ) ) * stress_old ) +
                                        ( ( average_viscoelastic_viscosity / average_elastic_shear_moduli[i] ) *
                                          ( symmetrize(rotation * Tensor<2,dim>(stress_old) ) - symmetrize(Tensor<2,dim>(stress_old) * rotation) ) );

    // Stress averaging scheme to account for difference between fixed elastic time step
    // and numerical time step (see equation 32 in Moresi et al., 2003, J. Comp. Phys.)
    if (use_stress_averaging == true)
      {
        stress_new = ( ( 1. - ( dt / dte ) ) * stress_old ) + ( ( dt / dte ) * stress_new ) ;
      }
```
