### ISSUE TITLE
mpi4py v h5py

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#50]
I have been struggling to get consistent versions of h5py / mpi4py on my El Capitanio mac os installation and the error appears to be one associated with inconsistent mpi versions locked in during compilation.

This feels pretty fragile and I wonder if it will be necessary to build our own mpi4py.

**Comment by jmansour** [comment]
yeah, this can be quiet fragile. the way forward may indeed by to compile up our own mpi4py.

**Comment by RebeccaFarrington** [comment]
yeah, I'm having problems here as well.  Louis, did you find a work around?  

I've compiled my own mpi4py (it passes tests etc), but still having problems configuring uw2.

[rfarrington@6250L-124341-M 01:41 pm] libUnderworld $ ./configure.py 
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
Checking for package H5py... --------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[6250L-124341-M.local:70085] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[rfarrington@6250L-124341-M 01:41 pm] libUnderworld $

**Comment by lmoresi** [comment]
I still haven't got h5py working at all on my laptop (10.11) not with underworld anyway.

Can we get a test piece of code to see if it is actually underworld or h5py that is broken ?



Sent from my iPhone

On 25 Feb 2016, at 13:46, RebeccaFarrington <notifications@github.com<mailto:notifications@github.com>> wrote:


yeah, I'm having problems here as well. Louis, did you find a work around?

I've compiled my own mpi4py (it passes tests etc), but still having problems configuring uw2.

[rfarrington@6250L-124341-M 01:41 pm] libUnderworld $ ./configure.py
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes

Checking for package Mpi4py... yes

It looks like orte_init failed for some reason; your parallel process is
likely to abort. There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems. This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

orte_ess_init failed

--> Returned value Error (-1) instead of ORTE_SUCCESS

Checking for package H5py... --------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort. There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems. This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

ompi_mpi_init: ompi_rte_init failed

--> Returned "Error" (-1) instead of "Success" (0)

*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
*** and potentially your MPI job)
[6250L-124341-M.local:70085] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[rfarrington@6250L-124341-M 01:41 pm] libUnderworld $
