### ISSUE TITLE
Running a not-included jupyter notebook from binder

### ISSUE THREAD

**Issue by Artshap** [underworldcode/underworld2#504]
Hi guys,

I'm a TA for a geoscience course at the UNSW Sydney. For one of the tutorials, we want students to run underworld from binder, but use a jupyter notebook of our own.

I am very new to docker and I am a bit struggling to make this work. Best thing I could come up with by now was forking your repo and adding a 

`ADD https://github.com/Artshap/underworld2/blob/master/docs/examples/05_Rayleigh_Taylor_modified.ipynb /temp_files/`

line to dockerfile in the main folder. From the log binder does see that line, but the file is not there in the final container.

Any chance you could suggest something? I saw the docker tutorials in your blog, but couldn't see it covering specifically this case.

Best Regards,
Artur

**Comment by lmoresi** [comment]
You can always get your students to upload your file if the class is up to that.

But, agreed, the easiest way is to have your own repo and add extra files at the binder-launch time.

L

On 15 Sep 2020, 11:43 AM +1000, Artshap <notifications@github.com>, wrote:

Hi guys,

I'm a TA for a geoscience course at the UNSW Sydney. For one of the tutorials, we want students to run underworld from binder, but use a jupyter notebook of our own.

I am very new to docker and I am a bit struggling to make this work. Best thing I could come up with by now was forking your repo and adding a

ADD https://github.com/Artshap/underworld_copy/blob/master/docs/examples/05_Rayleigh_Taylor_modified.ipynb /temp_files/

line to dockerfile in the main folder. From the log binder does see that line, but the file is not there in the final container.

Any chance you could suggest something? I saw the docker tutorials in your blog, but couldn't see it covering specifically this case.

Best Regards,
Artur

**Comment by Artshap** [comment]
The core problem (or I maybe it is a feature) is that it is building an image based on clean docker hub image and I can't seem to be able to modify the content in anyway so that it is added during the build.

Please let me know if I am incorrect and that there are parameters available to be changed in Dockerfile so that it will use the examples folder from my repo instead of default one.

Artur

**Comment by lmoresi** [comment]
The really easy way is to build your Docker FROM the underworld one and add your content from your repo afterwards. That will also help because binder will just have to get the uw docker image and do a tiny amount of extra processing.

On 15 Sep 2020, 12:10 PM +1000, Artshap <notifications@github.com>, wrote:

The core problem (or I maybe it is a feature) is that it is building an image based on clean docker hub image and I can't seem to be able to modify the content in anyway so that it is added during the build.

Please let me know if I am incorrect and that there are parameters available to be changed in Dockerfile so that it will use the examples folder from my repo instead of default one.

Artur

**Comment by Artshap** [comment]
@lmoresi thank you! When I started googling the approach you have suggested I saw that I was doing a correct thing from the beginning. I was just missing a dot before the temp folder name. Changing the line to
`ADD /docs/examples/05_Rayleigh_Taylor_modified.ipynb ./temp_files/`
solved the issue!
