### ISSUE TITLE
How to save velocity field at each time step? 

### ISSUE THREAD

**Issue by ejhgeo** [underworldcode/underworld2#509]
Hi, 
I am running a simple cross-sectional flow model for a subduction zone with a velocity boundary condition. I would like to be able to visualize the full velocity field vectors at different time-steps, not just the final one. To do this, I have tried to save the velocityField after each iteration by appending it to a preallocated empty list. This method works perfectly fine for other variables that I am storing with each iteration, but for some reason, when I try to save the velocityField, all the velocityFields stored in the list are the same as the final one. I'm not even sure how that is possible since at the point when I am storing the solution for each iteration, it doesn't even know what the final solution is yet (unless my understanding there is wrong). Somehow it's just storing the final solution for every iteration instead, even though when I print velocityField.data as the code it running, the velocity fields for each iteration are all different! I have tried storing both just velocityField and velocityField.data (which I would imagine should work, since the latter is just a numpy array), and still I have the problem. 

Is there a proper Underworld way of storing or accessing the velocityField for each or for select time-steps? I would imagine it is since visualizing the model at different points in time is a pretty standard thing that people do. As a mesh variable, is the velocityField defined in such a way that whatever the final solution is, it just redefines any variable that references it to that final solution? I see the slab subduction example stores the results for time-steps by saving everything to a file and figure, but is there a way to just store the velocityField to a list or array without having to create the figure a priori, that way the figure can be made and changed as needed after the fact? Any help is much appreciated. I can attach my code if needed. Thanks!

**Comment by jmansour** [comment]
It sounds to me like you're simply storing the handle to the Python object.  So for example:
```python
import numpy as np

steps = []
data = np.zeros(1)

data[:] = 1.2345
steps.append(data)
data[:] = 6.7890
steps.append(data)

print("data:")
for step in steps:
    print(step)

print("")
print("ids:")
for step in steps:
    print(id(step))
```
prints
```shell
data:
[6.789]
[6.789]

ids:
140639003640176
140639003640176
```

Firstly, note the object `id()` being printed is the same, because the same object appears twice in the list. So when we print the object's data, we simply see the data in its *current* state. The state it was in when we initially added it to the list is irrelevant. 

If you instead want to record the state of the object at previous steps, you will need to take a copy of the data at each step:
```python
import numpy as np

steps = []
data = np.zeros(1)

data[:] = 1.2345
steps.append(data.copy())
data[:] = 6.7890
steps.append(data.copy())

print("data:")
for step in steps:
    print(step)

print("")
print("ids:")
for step in steps:
    print(id(step))
```
which now prints
```shell
data:
[1.2345]
[6.789]

ids:
140364302825392
140364275100048
```

Keep in mind that taking a copy of heavy data objects at each step can quickly overwhelm your system's available memory. Depending on the size of your job and number of steps you wish to record (and also memory available on the machine), it may be wiser to save the data to disk using the variables `save()` method or directly save the numpy array preferably using `h5py`.  Also if it is sufficient, rendering images of the fields is a much lighter approach.
