### ISSUE TITLE
How to get rid of password or token request?

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#512]
Hi there,

Is there an easy way to get rid of the page that request the password or token when we open the UW2. The attachment contain the page that I talking about. This page is pop up sometimes when I run UW2, but not always. Generally, what I do is copy the token from the kitematic and paste it here. As of my knowledge, soon the kinematic will not be used if I am not wrong. (May be it has already removed. :-)).

cheers
Pras

<img width="1379" alt="Screen Shot 2020-10-22 at 4 00 04 pm" src="https://user-images.githubusercontent.com/25965506/96826819-e4629480-147f-11eb-822c-ae740cdcb32b.png">

**Comment by jmansour** [comment]
Hi Pras

If you're using Docker, you can disable the security requirement.  There's some discussion here:

https://github.com/jupyter/notebook/issues/2254

But let us know if you struggle. 

Note that it can be a big security risk having the token auth disabled, as Jupyter is starting a web service that allows users to use your computer. If someone else can access this web service (and no token is required), they can use your computer.  We've previously had users end up with crypto-miners running on their machines due to this, so proceed carefully.

**Comment by Prasanna2989** [comment]
Thanks John. If I kept it as it is, Is there a way to find the token other than using kitematic?

**Comment by jmansour** [comment]
You might want to look at creating a fixed password:

https://jupyter-notebook.readthedocs.io/en/stable/public_server.html?highlight=password#preparing-a-hashed-password

Note however that since you're running in Docker, every time you create a new container, the modifications outlined in the link above will be lost.  So what you might need to do, is generate the modifications as per the link, and then create a new image from the container (the new image will have your changes recorded).   I'm not sure if this is possibly from Kitematic, however you can use `docker ps` to find which container is running (it will have your modifications), and then use `docker commit` to create a new image from this container.  Refer to the respective `--help` for further info on those commands.  

Let me know how you go.

**Comment by julesghub** [comment]
One can find the token via the command line. You just need the `container id` in this command
   `docker exec <CONT_ID> jupyter-notebook list`

As mentioned above keeping this security feature on is recommended.

**Comment by Prasanna2989** [comment]
Thanks Julian. Yes. This helps a lot.

**Comment by Prasanna2989** [comment]
Thank you all.
