### ISSUE TITLE
How to get the number of tracers in each cell

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#513]
Hi all,

For a case, I need to check how many tracers of a certain kind (flavour) exist in each cell. I need to know these numbers to check how using tracer ratio or marker-in-cell methods influence the entrainment of a dense chemical layer. Is there any simple way to get these numbers? Thanks a lot.

Best regards,
Ting

**Comment by jmansour** [comment]
Hi Ting

Perhaps the `owningCell` data attribute on the swarm might be useful? 

```python
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian()
swarm = uw.swarm.Swarm(mesh)
swarm.populate_using_layout(uw.swarm.layouts.PerCellGaussLayout(swarm,5))
import numpy as np
values, counts = np.unique(swarm.owningCell.data, return_counts=True)
```

Note however in parallel that you will need to be somewhat more careful, as the cells ids reported by `owningCell` will be local identifiers.  This may be sufficient for your purposes, but if it isn't you can map to global ids using `mesh.data_elgId`.

**Comment by tingyang2004** [comment]
Thanks John,

This is just what I needed.
Combining the owningCell data attribute and the materialType variable will let me get the number of a certain type of tracer in each cell conveniently.

Best regards,
Ting

**Comment by tingyang2004** [comment]
Issue solved. I am closing this issue now.

**Comment by lmoresi** [comment]
Ting, I wonder if you should chat to Haibin about his work on averaging in the PIC method.
For rheology rather than composition … but there maybe a useful discussion you two can have.
On 29 Oct 2020, 1:18 PM +1100, tingyang2004 <notifications@github.com>, wrote:

Thanks John,

This is just what I needed.
Combining the owningCell data attribute and the materialType variable will let me get the number of a certain type of tracer in each cell conveniently.

Best regards,
Ting

**Comment by tingyang2004** [comment]
Thanks, Louis, I will call Haibin later.
