### ISSUE TITLE
Invert vertical axis in model setup?

### ISSUE THREAD

**Issue by ejhgeo** [underworldcode/underworld2#514]
Hi, 
I am wondering, is there any way to invert the vertical axis when we set up our model domain in Underworld. Currently, when I set up my mesh and swarms, zero is at the bottom of the domain and the maximum height is at the top, but I need it to be zero at the top (i.e. sea level) and positive downwards with depth into the Earth, as this is more intuitive for most Earth problems and necessary for the data I'm using with Underworld. Is there a way to explicitly set up the model domain to be positive downwards without actually making all the depths negative? If not, I can make all my data negative and just use a range of -z km to 0 km and that should probably work, but if there's a way to formally set the mesh to be positive downwards, that would be great. Thanks.

**Comment by lmoresi** [comment]
This is the coordinate system that we used in Citcom, which is natural in 2D but ended up being left-handed in the way that it was implemented (so awkward because of things like negative Jacobians in the elements).

In UW, you have the advantage of Functions which means you can define functions to represent your coordinate system if you want and have d = 1.0 - z, for example for most of your own set up while leaving and x,y,z coordinate system in place in the background. This will not be very expensive because it does not then change anything in the solvers. You would also need to flip the velocity solution but that can be done with functions.

L



On 12 Nov 2020, 2:06 PM +1100, ejhgeo <notifications@github.com>, wrote:

Hi,
I am wondering, is there any way to invert the vertical axis when we set up our model domain in Underworld. Currently, when I set up my mesh and swarms, zero is at the bottom of the domain and the maximum height is at the top, but I need it to be zero at the top (i.e. sea level) and positive downwards with depth into the Earth, as this is more intuitive for most Earth problems and necessary for the data I'm using with Underworld. Is there a way to explicitly set up the model domain to be positive downwards without actually making all the depths negative? If not, I can make all my data negative and just use a range of -z km to 0 km and that should probably work, but if there's a way to formally set the mesh to be positive downwards, that would be great. Thanks.

**Comment by julesghub** [comment]
Closing this issue. Please reopen if it's still a problem.
