### ISSUE TITLE
Checking for package NumpyPk no when installing UW on Centos7

### ISSUE THREAD

**Issue by JedWang06** [underworldcode/underworld2#529]
Hi all,
Recently, I met this issue when  installing uw2.10 on centos7, the specific error showed that checking for package NumpyPk no, any suggestions? I have read the two related questions, but I think it is different from our problem. Let me know if you need more information. Thanks a lot.

Best regards,
Jed

**Comment by JedWang06** [comment]
[config.log](https://github.com/underworldcode/underworld2/files/6101238/config.log)
![config](https://user-images.githubusercontent.com/80035635/110320084-c1a9d480-804a-11eb-91bf-dc1f33ab8335.png)

**Comment by longgangfan** [comment]
I met this problem recently. The problem is something mentioned in your config.log lines:374-376, 401-403, 431-433 ...
At first it occurred when I use a "pyenv virtualenv".  Then I resolved it, by changing to the system python 3.9. Maybe this is the problem, I cannot confirm it.


**Tips:**
1. **development branch** is important.
The git clone master branch just check the latest python <3.8, and if you compile in this branch, more problems will occur.
So, if you cloned all the branches, please checkout to the **development branch**.
or, use the following command to pull the development branch.
`git clone --single-branch --branch development https://github.com/underworldcode/underworld2.git`
2. **pip installed binary packages** could intriguer kernel dump.
The pip installing is recommended for some dependent packages in the official installation document. But, for me, some binary packages (lavavu, PETSc) from pip could intrigue  the kernel dump (like _"MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD with errorcode 50176059"_), so I compiled them myself (Because there are no the packages on my system package manager). And everything is OK. If you want to use pip, please add the --no-binary=:all:.
In a word, the system package manager provides a better choice, then pip and compiling from source.

**Comment by jmansour** [comment]
Hi @JedWang06. Did you find a solution to this problem?  I assume `numpy` is installed?  Did you simply try `pip install underworld`? 

And thanks for tips @longgangfan.

**Comment by longgangfan** [comment]
> Hi @JedWang06. Did you find a solution to this problem? I assume `numpy` is installed? Did you simply try `pip install underworld`?
> 
> And thanks for tips @longgangfan.

Finally, I got the true answer. When you install your python, please enable the key "--enable-shared". And this is the point to resolve to NumpyPk Not Found.
https://github.com/openai/go-vncdriver/issues/16#issuecomment-272423954

I said above, "changing to the system python". Because the system python was compiled with the key  "--enable-shared". Good Luck!

**Comment by JedWang06** [comment]
Following the two tips, I have already solved the problem @jmansour.
And thanks for your tips @longgangfan.

**Comment by jmansour** [comment]
Thanks @JedWang06
