### ISSUE TITLE
python module install in docker images

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#547]
Hi all,

I was trying to install the numba module to accelerate some for loops that seem inevitable. However, I got the following issue saying that I was not permitted to do the installation. Is there a way to solve this? Thanks a lot.

Ting

![image](https://user-images.githubusercontent.com/26615840/123401218-2462b400-d5d9-11eb-989e-1d38134358a5.png)

**Comment by julesghub** [comment]
Hi Ting, are you running this in the docker or another environment?

**Comment by tingyang2004** [comment]
I was running it in the docker.

**Comment by jmansour** [comment]
@tingyang2004 you'll have to use user `root` and start in _privileged_ mode to install packages:

```shell
~$  docker run -it --privileged --user root  underworldcode/underworld2 /bin/bash
jovyan ~$ pip install numba
```
I'm not exactly sure how to do this from Kitematic if you're using that, but it should be possible. 

@julesghub, I think for the next release we should `chmod -R ugo+rwx /opt` so that users can install whatever they required in `/opt` without root privileges.  Thoughts?

**Comment by tingyang2004** [comment]
John's method works.

Thanks, both.
