### ISSUE TITLE
checkpointing only single precision

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#62]
Shouldn't these just replicate the data type of the checkpointed object?

**Comment by jmansour** [comment]
Also, shouldn't the mesh routines that return global id maps be based upon long int variable objects?

Mesh_GenerateNodeGlobalIdVar
Mesh_GenerateElGlobalIdVar
Mesh_GenerateENMapVar

I'll note that we don't currently have a Variable_DataType_LongInt.  I guess it won't be an issue until we hit 2147483647 nodes.

**Comment by julesghub** [comment]
yep i agree with this. Can't recall why i didn't code it to reflect the
data type of the checkpoint object. Can look into it.

**Comment by jmansour** [comment]
i think i've sorted it now (except for the longint thing).  will commit this arvo.

**Comment by lmoresi** [comment]
Can this be closed ?

**Comment by jmansour** [comment]
somewhat.  the main checkpointing issue is fixed, but these global indices
are still based upon int types, where they really should be long int types.

currently, the underlying data type infrastructure does not support long
ints, but not hugely difficult to generalise.

**Comment by lmoresi** [comment]
OK - just doing some housekeeping.




On 19 March 2016 at 8:15:00 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

somewhat. the main checkpointing issue is fixed, but these global indices
are still based upon int types, where they really should be long int types.

currently, the underlying data type infrastructure does not support long
ints, but not hugely difficult to generalise.

On Saturday, 19 March 2016, Louis Moresi <notifications@github.com> wrote:

> Can this be closed ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/underworldcode/underworld2/issues/62#issuecomment-198541796>
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/62#issuecomment-198544351>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>
