### ISSUE TITLE
defining vector function object

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#63]
The current function passing interface doesn't allow for the creation of tuples (vectors) of functions.
It breaks and gives a cryptic error. 

Example, not implement yet:
ss = uw.systems.SteadyStateHeat(    temperatureField = tField,
                                    fn_diffusivity   = 1.0,
                                    fn_heating      = 1.0,#(2.0+2.0*uw.function.coord()[0]),
                                    fn_flux             =  (uw.function.coord()[0], uw.function.coord()[0]),
                                    conditions       = [bc, nbc] )

fn_flux blows up

Fix would be to allow for tuples of function to be passed, plus better error messaging.

**Comment by lmoresi** [comment]
Is this due to the requirement that tuples are immutable ?  Maybe you need a list ?

L


On 4 March 2016 at 4:34:43 PM, julesghub (notifications@github.com<mailto:notifications@github.com>) wrote:

The current function passing interface doesn't allow for the creation of tuples (vectors) of functions.
It breaks and gives a cryptic error.

Example, not implement yet:
ss = uw.systems.SteadyStateHeat( temperatureField = tField,
fn_diffusivity = 1.0,
fn_heating = 1.0,#(2.0+2.0*uw.function.coord()[0]),
fn_flux = (uw.function.coord()[0], uw.function.coord()[0]),
conditions = [bc, nbc] )

fn_flux blows up

Fix would be to allow for tuples of function to be passed, plus better error messaging.

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/63>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
No it's just a limitation in the current function interface.  We can extract components from vector functions

```
hot = fn.misc.Constant( (0.2,0.3) )
tub0 = hot[0]
tub1 = hot[1]
```

But we cannot (currently) go in the other direction.  
```
tub0 = fn.misc.Constant( 0.2 )
tub1 = fn.misc.Constant( 0.3 )
hot = fn.misc.Scalar_to_Vector_Not_Yet_Implemented(tub0, tub1)

```

**Comment by jmansour** [comment]
a725983d7ac7c2e65e9b8c24f55ae62eabad11ef
