### ISSUE TITLE
Mesh Advection Project

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#64]
This is general ticket for a bunch of things that need to happen for Mesh Advection.

Mechanism to move mesh, we should use scipy
Mechanism to advect particles using new advection style
Compressibility
LFT, Luke Mondy’s stuff needs to be reproducible.

**Comment by lmoresi** [comment]
Compressibility could be quite a big deal - what did you have in mind ?

**Comment by jmansour** [comment]
at this stage we're only talking about the pseudo compressibility to allow
non soloidal velocity fields.   ala underworld1.

**Comment by lmoresi** [comment]
Let’s be careful with that. It was so broken that it was quite misleading.


On 19 March 2016 at 8:17:58 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

at this stage we're only talking about the pseudo compressibility to allow
non soloidal velocity fields. ala underworld1.



—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/64#issuecomment-198545810>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by RebeccaFarrington** [comment]
I'm going to break this out into it's components ...
