### ISSUE TITLE
Trouble building Underworld2 on CentOS 7: HDF5 

### ISSUE THREAD

**Issue by cousins** [underworldcode/underworld2#65]
Hi, 

I'm trying to install on a CentOS 7 system. Tried with straight HDF5 (non-parallel) from hdfgroup.org but it says it needs to be parallel. Since HDF5 is listed as optional I unloaded the HDF5 environment module so the configure script wouldn't find it but configure.py says it can't find HDF5 now and won't continue. It seems that HDF5 is *not* optional. Or is there a way to tell it to not use HDF5? If we don't have a parallel file system can we not install Underworld2?

I sent an email to John Mansour and he recommended sending this to the Github issue tracker. He also said:

One thing you can try is to import the 'h5py' python module directly, and see what error messages it returns.  Do this in the python interpreter from the topmost Underworld2 directory.

I don't see h5py in what I compiled when I installed HDF5 and I also don't see it listed in the dependencies for Underworld2 so I'm confused by this. now I see that there is a h5py_ext directory in the libUnderworld directory. Also, now I see that the installation of Python I have (Anaconda) has h5py installed. 

So, when John says: "import the 'h5py' python module directly" I'm not sure what he means. Do I add that to the configure.py script at the beginning?

Is there a document showing what exactly needs to be installed to be able to build this software?

Thanks,

Steve

**Comment by lmoresi** [comment]
I think what John means is that you should first of all try to get a parallel hdf5 installation, then add mpi4py and h5py.
But you do need to have hdf5 - it’s not really optional any more.

If you can then do something like

% ipython
[1] import h5py

then you can appeal to us to help with the underworld installer.

The reason john is suggesting doing this from the underworld directory is that we bundle a version of h5py which we will build as needed but it will not necessarily be in the python path.

L






On 16 March 2016 at 3:17:28 AM, Steve Cousins (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi,

I'm trying to install on a CentOS 7 system. Tried with straight HDF5 (non-parallel) from hdfgroup.org<http://hdfgroup.org> but it says it needs to be parallel. Since HDF5 is listed as optional I unloaded the HDF5 environment module so the configure script wouldn't find it but configure.py says it can't find HDF5 now and won't continue. It seems that HDF5 is not optional. Or is there a way to tell it to not use HDF5? If we don't have a parallel file system can we not install Underworld2?

I sent an email to John Mansour and he recommended sending this to the Github issue tracker. He also said:

One thing you can try is to import the 'h5py' python module directly, and see what error messages it returns. Do this in the python interpreter from the topmost Underworld2 directory.

I don't see h5py in what I compiled when I installed HDF5 and I also don't see it listed in the dependencies for Underworld2 so I'm confused by this. now I see that there is a h5py_ext directory in the libUnderworld directory. Also, now I see that the installation of Python I have (Anaconda) has h5py installed.

So, when John says: "import the 'h5py' python module directly" I'm not sure what he means. Do I add that to the configure.py script at the beginning?

Is there a document showing what exactly needs to be installed to be able to build this software?

Thanks,

Steve

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by cousins** [comment]
Thanks for the information. So is it that not only is HDF5 needed now but Parallel HDF5 is needed? What if we don't have a parallel file system to run it on? We're just running NFSv4 for home directories.

**Comment by cousins** [comment]
BTW, in ipython I can run:

import h5py

both in the underworld directory and outside of it.

**Comment by jmansour** [comment]
You will need to have the parallel version of hdf5 installed instead of the serial version.  It doesn't matter which file system you have.  Can you report what result you get from the following:

```python
import h5py
h5py.get_config().mpi
```

both in the Underworld2 directory, and outside it?  This will tell you whether you have a parallel build of h5py.

Is this for a personal computer (as opposed to a cluster computer)?  If so, it's probably a better option to simply use the docker installation, as this will save you all this headache.  I've written a tutorial here:

http://www.underworldcode.org/posts/Underworld-and-Dockers

and there's another one Louis put together for Windows/Mac systems using the Kitematic GUI:

http://www.underworldcode.org/posts/Underworld-and-Dockers2

**Comment by cousins** [comment]
Hi John,

OK. Thanks.Maybe at least change the README.md file to say that parallel HDF5 is required?

I got:

```
[cousins@viz3 ~]$ ipython
Python 2.7.10 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 18:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import h5py

In [2]: h5py.get_config().mpi
Out[2]: False

In [3]: quit
[cousins@viz3 ~]$ cd /opt/src/underworld2/
[cousins@viz3 underworld2]$ ipython
Python 2.7.10 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 18:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import h5py

In [2]: h5py.get_config().mpi
Out[2]: False

In [3]: quit
```

So, now, do I compile/install HDF5 from hdfgroup.org (which installs non-python bin, include, lib, share directories/files) or try to find a parallel version of h5py? As you can tell, Python isn't my strong suit. 

This is currently being installed on a visualization and pre/post processing machine for the cluster. If it works out I was planning on having it as a module that can be loaded for use on the cluster. Docker is out for this install.  

Again, Thanks.

Steve

**Comment by lmoresi** [comment]
I would suggest reading the h5py documentation (if you don’t fancy the docker route which is, actually, much simpler)

http://docs.h5py.org/en/latest/mpi.html

They take you through the hdf5, mpi4py and h5py installation (and testing).

By default, the bleeding edge (2.6.0) version of h5py supports all of the parallel features but 2.5.0 does not and this is often what the package managers default to.

L


On 16 March 2016 at 10:06:37 AM, Steve Cousins (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi John,

OK. Thanks.Maybe at least change the README.md file to say that parallel HDF5 is required?

I got:

[cousins@viz3 ~]$ ipython
Python 2.7.10 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 18:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import h5py

In [2]: h5py.get_config().mpi
Out[2]: False

In [3]: quit
[cousins@viz3 ~]$ cd /opt/src/underworld2/
[cousins@viz3 underworld2]$ ipython
Python 2.7.10 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 18:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import h5py

In [2]: h5py.get_config().mpi
Out[2]: False

In [3]: quit



So, now, do I compile/install HDF5 from hdfgroup.org (which installs non-python bin, include, lib, share directories/files) or try to find a parallel version of h5py? As you can tell, Python isn't my strong suit.

This is currently being installed on a visualization and pre/post processing machine for the cluster. If it works out I was planning on having it as a module that can be loaded for use on the cluster. Docker is out for this install.

Again, Thanks.

Steve

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/65#issuecomment-197062166>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by cousins** [comment]
So is the requirement: parallel hdf5? parallel h5py? or both?

**Comment by lmoresi** [comment]
Both (parallel hdf5 and the latest h5py which supports the former). The h5py we bundled with underworld is a version known to work.

We are aware that this is something of a bleeding edge dependency but creating one file per process on highly parallel jobs has become a big headache for the scientists and also the admins of machines where inodes are in short supply. This seemed to be the best alternative.

L


On 16 March 2016 at 10:32:29 AM, Steve Cousins (notifications@github.com<mailto:notifications@github.com>) wrote:

So is the requirement: parallel hdf5? parallel h5py? or both?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/65#issuecomment-197068234>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Yep. So Underworld2 requires h5py (parallel), which itself requires hdf5 (parallel). 

Usually, Underworld will check for h5py, and then go ahead and build it if it can't find it.  It sounds like Underworld is not building it successfully, hence when you try 'import h5py' from the Underworld2 directory, it is probably simply loading the system version. 

Can you post your 'config.log' and 'config.cfg' (if it exists)?  Also, what is output to standard out?   I assume it's failing during the configuration step?  

Alternatively, if you'd like to make an account for me, I'm happy to log on and try sort out the details for you.

**Comment by cousins** [comment]
Hi Louis and John,

Made a lot of progress. Now a problem with:

`gLucifer/Viewer/src/Main/../VideoEncoder.h:102:31 error: use of enum 'PixelFormat' without previous declaration.
`

So, configure.py is happy after using a version of Python that does not already have h5py in it, plus recompiling everything (MVAPICH2, HDF5, PETSc, SZIP, LIBAVCODEC) with gnu compilers instead of Intel. As you said, it found that h5py was not installed so it pulled in your included version.

Then I ran ./scons.py and a lot of success compiling until the PixelFormat error. 

Any ideas about this one?

Thanks a lot,

Steve

FWIW, since you asked, here are my config.cfg and config.log (attached) files.

config.cfg:
`prefix = '/opt/modules/centos7/underworld2'
build_dir = 'build'
with_debugging = 1
with_profiling = 0
optimisation_flag = 'default'
with_warnings = 1
lib_type = 'shared'
CC = 'mpicc'
CXX = 'mpicxx'
CFLAGS = []
CXXFLAGS = '-std=c++11'
with_credo = 1
with_glucifer = 1
with_viewer = 1
with_geothermal = False
with_solvers = True
with_importers = False
with_spherical = False
with_viscoelastic = False
with_sdl = 1
with_x11 = 1
with_agl = 1
with_glut = 1
with_png = 1
with_avcodec = 1
with_gl2ps = 1
eptiming = 0
with_cautious_mode = 0
CPPPATH = ['/opt/modules/centos7/hdf5-parallel-gnu/1.8.16/lib/include', '/usr/include/libxml2', '/opt/modules/centos7/hdf5-parallel-gnu/1.8.16/include', '/usr/include/python2.7', '/opt/modules/centos7/petsc-gnu/3.6.3/include', '/usr/lib64/python2.7/site-packages/numpy/core/include']
LIBPATH = ['/opt/modules/centos7/hdf5-parallel-gnu/1.8.16/lib', '/opt/modules/centos7/petsc-gnu/3.6.3/lib', '/opt/centos7/mvapich2/2.1/gnu-4.8.3/lib', '/opt/centos7/gcc/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0', '/opt/centos7/gcc/gcc-5.2.0/lib64', '/opt/centos7/gcc/gcc-5.2.0/lib', '/usr/lib64/python2.7/site-packages/numpy/core/lib']
RPATH = ['/opt/modules/centos7/hdf5-parallel-gnu/1.8.16/lib', '/opt/modules/centos7/petsc-gnu/3.6.3/lib', '/usr/lib64/python2.7/site-packages/numpy/core/lib']
LIBS = ['python2.7', 'hdf5', 'xml2', 'm', 'lapack', 'blas', 'X11', 'pthread', 'ssl', 'crypto', 'mpifort', 'gfortran', 'quadmath', 'mpicxx', 'stdc++', 'dl', 'mpi', 'gcc_s', 'petsc']
CPPDEFINES = ['HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'DEBUG']
CFLAGS = []
CCFLAGS = ['-g', '-O0', '-Wall']
FRAMEWORKS = []
_RPATH = '${_concat(RPATHPREFIX, RPATH, RPATHSUFFIX, __env__)}'
SHLINKFLAGS = ['$LINKFLAGS', '-shared']
shared_libs = 1
static_libs = 0
`


[config.log.txt](https://github.com/underworldcode/underworld2/files/177013/config.log.txt)

**Comment by OKaluza** [comment]
Hi Steve, looks like you are missing a dependency for video output, probably libavcodec.
To work around it you can disable video output:
`./configure.py --with-avcodec=0`

A question for the others, does anyone use video encoding at all regularly? If not I might switch it to disabled by default.

**Comment by jmansour** [comment]
Yep, I'm in favour of disabling it by default, or even removing it
altogether if that makes sense.  It's pretty easy to hit a bunch of images
with ffmpeg from the command line.

**Comment by OKaluza** [comment]
I won't remove it entirely, it's actually had quite a bit of work put in to optimise settings for producing decent quality h264 video output, it skips the image generation step altogether and getting the settings right on ffmpeg can be a pain. That said I don't think there's really a need to build it with underworld by default, can always build the viewer standalone with video enabled.

**Comment by lmoresi** [comment]
My preference is to skip it by default … for those people using the viewer to dump movies, fine, but for people dumping frames from running scripts here and there and making up a movie from a series of restarts etc, I think the extra dependencies are too fragile.

I do appreciate the work involved though. I would suggest that we add a tutorial on the standalone viewer to the underworld docs pages.

L


On 17 March 2016 at 2:09:17 PM, OKaluza (notifications@github.com<mailto:notifications@github.com>) wrote:

I won't remove it entirely, it's actually had quite a bit of work put in to optimise settings for producing decent quality h264 video output, it skips the image generation step altogether and getting the settings right on ffmpeg can be a pain. That said I don't think there's really a need to build it with underworld by default, can always build the viewer standalone with video enabled.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/65#issuecomment-197672024>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by cousins** [comment]
I checked when I ran configure.py and libavcodec was found. I'll try without it and see if it is needed later (by the person I'm setting this up for).

Here is the output I got from configure.py:

[root@viz3 libUnderworld]# ./configure.py --prefix=/opt/modules/centos7/underworld2
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Exception RuntimeError: 'generator ignored GeneratorExit' in <generator object gen_envs at 0x1f6e3c0> ignored
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... yes
Checking for package libPNG... yes
Checking for package libavcodec... yes
Checking for package gl2ps... yes
Checking for package X11... yes
Checking for package SDL... yes
Checking for package Glut... yes
Checking for package OpenGL... yes

Saved configuration: "config.cfg"
  Flags imported from PETSc:
   LIBPATH: ['/opt/centos7/mvapich2/2.1/gnu-4.8.3/lib', '/opt/centos7/gcc/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0', '/opt/centos7/gcc/gcc-5.2.0/lib64', '/opt/centos7/gcc/gcc-5.2.0/lib', '/opt/centos7/mvapich2/2.1/gnu-4.8.3/lib', '/opt/centos7/gcc/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0', '/opt/centos7/gcc/gcc-5.2.0/lib64', '/opt/centos7/gcc/gcc-5.2.0/lib']
   LINKFLAGS: ['-Wl,-rpath,/opt/centos7/mvapich2/2.1/gnu-4.8.3/lib', '-Wl,-rpath,/opt/centos7/gcc/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0', '-Wl,-rpath,/opt/centos7/gcc/gcc-5.2.0/lib64', '-Wl,-rpath,/opt/centos7/gcc/gcc-5.2.0/lib', '-Wl,-rpath,/opt/centos7/mvapich2/2.1/gnu-4.8.3/lib', '-Wl,-rpath,/opt/centos7/gcc/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0', '-Wl,-rpath,/opt/centos7/gcc/gcc-5.2.0/lib64', '-Wl,-rpath,/opt/centos7/gcc/gcc-5.2.0/lib', '-Wl,-rpath,/opt/centos7/mvapich2/2.1/gnu-4.8.3/lib']
  C compiler:     'mpicc'
  C flags:        -g -O0 -Wall
  C preprocessor: ['HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'DEBUG']
  Libraries: ['python2.7', 'hdf5', 'xml2', 'm', 'lapack', 'blas', 'X11', 'pthread', 'ssl', 'crypto', 'mpifort', 'gfortran', 'quadmath', 'mpicxx', 'stdc++', 'dl', 'mpi', 'gcc_s', 'petsc']

Saved configuration: "viewer.cfg"
  C preprocessor: ['HAVE_LIBPNG', 'HAVE_LIBAVCODEC', 'HAVE_GL2PS', 'HAVE_X11', 'HAVE_SDL', 'HAVE_GLUT', 'HAVE_OPENGL', 'DEBUG']
  Libraries: ['GL', 'GLU', 'glut', 'SDL', 'X11', 'gl2ps', 'avcodec', 'avutil', 'avformat', 'png']

*****************************************************************
* Successfully configured.                                      *
*                                                               *
* Note that basic usage metrics are dispatched when you use     *
* Underworld.                                                   *
* To opt out, set the UW_NO_USAGE_METRICS environment variable. *
* See PRIVACY.md for full details.                              *
*                                                               *
* Now run './scons.py' to build.                                *
*****************************************************************

**Comment by cousins** [comment]
That did the trick. Any idea why it wouldn't work since it was able to find libavcodec?

Thanks for all of your help.

**Comment by OKaluza** [comment]
Hi Steve, unfortunately there are so many versions of libavcodec out there with incompatible definitions/symbols that it's almost impossible to keep up with them all and the configure process isn't smart enough to detect a version that appears ok but isn't.  
I'll try building on a CentOS 7 VM when I get a chance to see if I can duplicate the issue and add a fix for this particular version to the growing list here https://github.com/OKaluza/LavaVu/blob/master/src/VideoEncoder.h#L49
Also, it will be disabled in the build by default soon so won't be an issue for most.

**Comment by RebeccaFarrington** [comment]
@cousins 
if this issue has been resolved do you mind if we close this ticket?  
Thanks

**Comment by cousins** [comment]
Hi, I have been able to get Underworld2 to compile now but it looks like the problem is still there. The problem is that the documentation (README.md file) states HDF5 is optional. I think it should be changed to say "Parallel HDF5 is required". Also, mpi4py is required I think.

**Comment by jmansour** [comment]
We have started a new ticket (#86) which will address these shortcomings, so I will go ahead and close this one.
