### ISSUE TITLE
Issue with simple 3D model

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#67]
Hi all,

I was trying to test out some complex boundary conditions in a 3D UW2 model, and I was getting out a fairly crazy velocity field. The model is simple: two different materials (air and rock), each have isovisc rheologies (1e18 Pa.s, 1e20 Pa.s), with different densities (1  kg/m^3, 2800 kg/m^3),  - so I switched back to using more normal boundary conditions: freeslip, pulling on the I walls - and I still get a very crazy velocity field. The top of the model is open.

The only complication I can see is that I have Z as the vertical axis. Other than that, I'm not sure if I'm not setting up the boundary conditions right, but from looking at the examples and docs, it should be OK.

Here is the ipython notebook:
https://gist.github.com/OlympusMonds/d94722ae4c7ae0abce98

The model only takes a few minutes to run on a single CPU. I'm using the underworld-dev docker container.

Any help would be much appreciated!

Cheers,
Luke

**Comment by OlympusMonds** [comment]
Switching to Y as the vertical axis has no effect.

**Comment by jmansour** [comment]
Hi Luke

I had a bit of play around with your model.. I'm not exactly sure what's going on, but I'd check to see how your buoyancy forces scale relative to your viscous dissipation. If these are on very different scales, then your model will effectively be free slip everywhere, and you're velocities will become astronomical and possibly just reflect solver noise.

**Comment by lmoresi** [comment]
Though it may be slow, try using mumps and a high penalty. This will reduce the influence of solver settings and you can see if the scaling is very poor.

Viscous dissipation ?  Maybe turn that off until the issues are clearer / just run one time step.

Sent from my iPhone

On 18 Mar 2016, at 04:14, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Luke

I had a bit of play around with your model.. I'm not exactly sure what's going on, but I'd check to see how your buoyancy forces scale relative to your viscous dissipation. If these are on very different scales, then your model will effectively be free slip everywhere, and you're velocities will become astronomical and possibly just reflect solver noise.

**Comment by OlympusMonds** [comment]
Thanks for the feedback. 
John, I'm not sure what you mean by viscous dissipation - do you mean the actual viscosity of the material? I'm using natural values for everything (except for the air visc), so they should be appropriately scaled in that sense, even if it's not great for the solver.

Louis, I tried as you said, with identical results.

I moved to a 2D version of the model for faster testing (https://gist.github.com/OlympusMonds/7da355682612baf00ef0) - the thing that makes the models not explode (retain reasonable velocities) is the the timestep length. Reducing the dt by a factor of 10 means the models can stay stable - although they are still more variable than I would expect; I feel like I've done the same sort of model in UW1.8, but I can't find the exact example.
Here are some results:
https://www.dropbox.com/sh/047ytqiukqv087d/AACwG20G8R6XnMH9V8IUBb-ta?dl=0
Each folder has an image at time = 0, and time ~ 3.115569e12 seconds.

Any ideas?

**Comment by lmoresi** [comment]
By “natural units” do you mean SI ?  It’s not obvious to me that this is really the natural set of units for this problem since people usually think in GPa, km, Myr etc etc. In order to bring things into numbers within a hailing distance of 1 !

I did look into this when I first was putting ellipsis together. The numerical noise is enormously problematic if you have viscosities specified in Pa.s and so forth. I suspect this is what you are actually having problems with.

To get around this we did a number of things: 1) the whole system of units / scaling that was in uw1.x which is pretty cumbersome and we haven’t planned on implementing in uw2 and 2) matrix rescaling to try to “precondition” these big scale factors out of the problem. This can work but it may not because some of the trouble might be numerical noise coming through as the matrices are constructed not when they are solved.

What I tend to do is to rescale in python which is option (x) because the underworld team doesn’t have to implement anything. Maybe we should give some examples though. Probably my job … maybe I can do this as an exercise for the class when I teach it soon.

L


On 19 March 2016 at 7:41:36 pm, Luke Mondy (notifications@github.com<mailto:notifications@github.com>) wrote:

Thanks for the feedback.
John, I'm not sure what you mean by viscous dissipation - do you mean the actual viscosity of the material? I'm using natural values for everything (except for the air visc), so they should be appropriately scaled in that sense, even if it's not great for the solver.

Louis, I tried as you said, with identical results.

I moved to a 2D version of the model for faster testing (https://gist.github.com/OlympusMonds/7da355682612baf00ef0) - the thing that makes the models not explode (retain reasonable velocities) is the the timestep length. Reducing the dt by a factor of 10 means the models can stay stable - although they are still more variable than I would expect; I feel like I've done the same sort of model in UW1.8, but I can't find the exact example.
Here are some results:
https://www.dropbox.com/sh/047ytqiukqv087d/AACwG20G8R6XnMH9V8IUBb-ta?dl=0
Each folder has an image at time = 0, and time ~ 3.115569e12 seconds.

Any ideas?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/67#issuecomment-198668522>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>
