### ISSUE TITLE
Mesh advection

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#69]
@jmansour and @garethkennedy  

this was part of the "mesh advection project"
[https://github.com/underworldcode/underworld2/issues/64](url)

**Comment by jmansour** [comment]
Two options here.  

1. Create a general TimeIntegrand. It will take a StgVariable (+1 STsP level up!) which will be integrated, and a function to define the derivatives.  So the mesh vertex data will be provided as the stgvariable, and the user will define the required velocity with which to advect the mesh. 

2. Do everything at the python level.  Numpy arrays will be the integrated quantity (mesh.data), functions will provide arrays of derivatives ( deriv_array = meshVelocity.evaluate(mesh) ), Scipy will provide the required integration routines (RK4 etc).   This would make Scipy a dependency.

**Comment by julesghub** [comment]
Number 2. has my vote - it follows more of the "outsource it" idea.

**Comment by lmoresi** [comment]
In the first instance, I would suggest (2) is more flexible.

Why not do that and then see if people find it too slow or cumbersome.

Scipy need not actually be a dependency. It is not so hard to code a 2nd order method as long as the points are not moving to new processors (If they are, then I think the python level is not going to work).

L




On 23 March 2016 at 10:23:08 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Two options here.

  1.  Create a general TimeIntegrand. It will take a StgVariable (+1 STsP level up!) which will be integrated, and a function to define the derivatives. So the mesh vertex data will be provided as the stgvariable, and the user will define the required velocity with which to advect the mesh.

  2.  Do everything at the python level. Numpy arrays will be the integrated quantity (mesh.data), functions will provide arrays of derivatives ( deriv_array = meshVelocity.evaluate(mesh) ), Scipy will provide the required integration routines (RK4 etc). This would make Scipy a dependency.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/69#issuecomment-200076208>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Yep, having a decent fallback is a good idea for where scipy isn't available.  

Nothing should be slow here, as operations should reduce to c-level calculations.  The scipy routines wrap odepack it seems:
http://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint

For particles (and other things), we would still need hooks (STsP level up!) to do things like fix particle ownership etc. This would be a call to our own C functions. The Scipy routines require us to provide a callable function to determine the derivatives, and we could integrate checks here for particles outside the domain etc.  Not exactly sure on details here though!

**Comment by OlympusMonds** [comment]
To go against the trend, how about 1? Integrating a variable through time is good for things like the finite strain. Loius does by hand in [here](https://github.com/underworldcode/underworld2/blob/ea4a93c1c6ba7244e1fa5d438345db67509911e9/docs/examples/1_08_ShearBandsSimpleShear.ipynb), but it doesn't necessarily match the advection order. Coincidentally just yesterday, I actually looked in the Integrand class to see if there was an integrationType of "time".

Regarding option 2 - I don't think I've ever had numpy installed without scipy, on linux or OSX, so it's probably not much of a dependency issue.

**Comment by jmansour** [comment]
Option 2 is really a superset (functionality wise) of option 1, so you could easily still integrate any variable, but you would use the numpy view of this variable, and you would construct a function to define the derivative.

**Comment by OlympusMonds** [comment]
Well OK, option 2!

**Comment by jmansour** [comment]
let's have a look at current method used for extension problems and decide if we're happy, if it should be done another way, or if some sort of explicit functionality should be provided.

**Comment by RebeccaFarrington** [comment]
Document best practise in an extension example.

**Comment by jmansour** [comment]
I think example 09 is fine, but perhaps a bit complex.  A very simply extension example would be a good idea.  I'll move this to the next milestone.
