### ISSUE TITLE
old unit tests

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#90]

**Comment by jmansour** [comment]
StGermain level c unit tests are passing.  (silver tracksuit pants power up level 7!)

The remaining tests either need to be fixed/updated or removed.

**Comment by lmoresi** [comment]
Get a hot tub, I am sure the silver track pants will be removed for that, John.

Good luck.

L


On 23 March 2016 at 9:14:16 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

StGermain level c unit tests are passing. (silver tracksuit pants power up level 7!)

The remaining tests either need to be fixed/updated or removed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/90#issuecomment-200054938>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by jmansour** [comment]
hot tub _sans_ silver track pants?  novel idea louis!

**Comment by RebeccaFarrington** [comment]
http://www.dialahottub.com.au/ <http://www.dialahottub.com.au/>
