### ISSUE TITLE
Fevariable interpolation in parallel

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#95]
I'm trying to read in a temperature field as an initial condition, i.e. map this to a mesh of variable resolution. The following loop is how I've tried to implement this, but in parallel it totally disfigures the TemperatureField...what's the preferred way of doing this / can anyone spot a bug here?

```
temperatureField.data[:] = 0.
for index, coord in enumerate(mesh.data):
    #Don't know mesh partitions in advance, and potentially these are different between 'real' and 'dummy' mesh
    try:
        temperatureField.data[index] = dummytemperatureField.evaluate([coord[0], coord[1]])
    except:
        pass
```

**Comment by jmansour** [comment]
That's because it will throw exceptions anywhere you are trying to evaluate it outside it's local domain. 

What you want to do is create your dummyTemperatureField on a non-partitioned partitioned mesh
Something like this:
```python
nonPartitionedMesh = uw.mesh.FeMesh_Cartesian(partitioned=False, etc)
dummytemperatureField = uw.mesh.MeshVariable( mesh, 1)
dummytemperatureField.load("somefile.h5")

mesh = uw.mesh.FeMesh_Cartesian( etc)
temperatureField = uw.mesh.MeshVariable(mesh,1)
temperatureField.data[:] = dummytemperatureField.evaluate(mesh)

```

**Comment by lmoresi** [comment]
Would it also be possible to treat the old nodal points as a swarm and solve the projection to the new mesh ?

This seems more scalable for massive parallel jobs.

L


On 23 March 2016 at 10:58:32 AM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

That's because it will throw exceptions anywhere you are trying to evaluate it outside it's local domain.

What you want to do is create your dummyTemperatureField on a non-partitioned partitioned mesh
Something like this:

nonPartitionedMesh = uw.mesh.FeMesh_Cartesian(partitioned=False, etc)
dummytemperatureField = uw.mesh.MeshVariable( mesh, 1)
dummytemperatureField.load("somefile.h5")

mesh = uw.mesh.FeMesh_Cartesian( etc)
temperatureField = uw.mesh.MeshVariable(mesh,1)
temperatureField.data[:] = dummytemperatureField.evaluate(mesh)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/95#issuecomment-200085879>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Also, depending on how different your resolutions are (IC vs simulation), you might like to consider using the MeshVariable_Projection to get a better representation of your IC variable onto your simulation variable.

```python
nonPartitionedMesh = uw.mesh.FeMesh_Cartesian(partitioned=False, etc)
dummytemperatureField = uw.mesh.MeshVariable( mesh, 1)
dummytemperatureField.load("somefile.h5")

mesh = uw.mesh.FeMesh_Cartesian( etc)
temperatureField = uw.mesh.MeshVariable(mesh,1)

projectedTemperatureField = uw.mesh.MeshVariable(mesh,1)
projector = uw.utils.MeshVariable_Projection( projectedTemperatureField, dummytemperatureField)
projector.solve()
temperatureField.data[:] = projectedTemperatureField.data[:]

```
Note that you should create the temporary projected variable for safety (#54) .  This requirement will be fixed sometime soon.

**Comment by jmansour** [comment]
Beat me to it Louis!  Yep.  Also, the type=1 projection (weighted residuals) is probably more appropriate in this case:
```python
projector = uw.utils.MeshVariable_Projection( projectedTemperatureField, dummytemperatureField, type=1)
```

**Comment by julesghub** [comment]
not sure how things go for the projection method but for safety Sync the
mesh field once you've put values on it. ie,

uw.libUnderworld.StgFEM._FeVariable_SyncShadowValues( temperatureField._cself )

If you want a reference see the load() function for a MeshVariable (under
_MeshVariable.py)

Depending on how successful this is we could use the projection method in
general for MeshVariable.load() ... for meshes that aren't the same.

**Comment by jmansour** [comment]
Lets keep thing simple and let users do this themselves.  

The sync thing is a good point.  We perhaps should provide a high level interface to this.  The alternative is to require context managers whenever mesh data is being modified:

```python
with temperatureField.modify_data():
   temperatureField[:] = 3.
```
which would then automatically do the sync.  Could get quiet cumbersome, but perhaps that's the price that needs to be paid to force safe usage.

**Comment by jmansour** [comment]
dan close this ticket when happy!
