### ISSUE TITLE
Code not compiling?

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#97]
Morning :)

I'm having some trouble compiling the code.  Help! 
The first issue seems to be fixed if I change the "X11Viewer" to "GlutViewer" in the below.

> gLucifer/Viewer/src/LavaVu.cpp:169:29: error: unknown type name 'X11Viewer'
>   if (!viewer) viewer = new X11Viewer();

second issue - i get the following (& haven't looked any further, sorry) 

> libUnderworldPy/PICellerator_wrap.cxx:8220:21: error: no member named 'timeIntegrator' in
>       'IntegrationPointsSwarm'
>   if (arg1) (arg1)->timeIntegrator = arg2;

**Comment by lmoresi** [comment]
Issue #1 - I found the same problem and sent Owen a pull request

Issue #2 - did you re-swig everything ?


On 29 March 2016 at 9:39:43 AM, RebeccaFarrington (notifications@github.com<mailto:notifications@github.com>) wrote:

Morning :)

I'm having some trouble compiling the code. Help!
The first issue seems to be fixed if I change the "X11Viewer" to "GlutViewer" in the below.

gLucifer/Viewer/src/LavaVu.cpp:169:29: error: unknown type name 'X11Viewer'
if (!viewer) viewer = new X11Viewer();

second issue - i get the following (& haven't looked any further, sorry)

libUnderworldPy/PICellerator_wrap.cxx:8220:21: error: no member named 'timeIntegrator' in
'IntegrationPointsSwarm'
if (arg1) (arg1)->timeIntegrator = arg2;

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/97>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by RebeccaFarrington** [comment]
no, no i did not!  I have now, and it’s all good :)

sorry all! :/

**Comment by lmoresi** [comment]
It’s not obvious to me why swig is broken out in this way - shouldn’t it be something we just do automatically as part of the build ?


On 29 March 2016 at 11:12:41 AM, RebeccaFarrington (notifications@github.com<mailto:notifications@github.com>) wrote:

no, no i did not! I have now, and it’s all good :)

sorry all! :/

> On 29 Mar 2016, at 11:04 AM, Louis Moresi <notifications@github.com> wrote:
>
> Issue #2 - did you re-swig everything ?


—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/97#issuecomment-202635965>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by RebeccaFarrington** [comment]
Yes, I agree.  It's listed as an action point in #82 ...

**Comment by OKaluza** [comment]
Sorry only just noticed this, I also fixed the above issue 1 and it's checked in now

**Comment by julesghub** [comment]
closing this ticket - it seems resolved
