### ISSUE TITLE
Failed in configuring the underworld in Mac OX

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#98]
When I run './configure.py' in underworld2 under Mac OX, there is an error 'Failed to locate required package libXML2'. But I do have install the libxml2 via 'brew install libxml2'. I don't know why this problem comes out.

**Comment by jmansour** [comment]
have you installed the xcode command line tools?  I believe you can just run `xcode-select --install` from the command line (or at least this used to be the case).

**Comment by wkillers** [comment]
yes, I have installed the command line tools. When I run 'xcode-select --install', it shows 'xcode-select: error: command line tools are already installed, use "Software Update" to install update.

**Comment by wkillers** [comment]
I found what's the problem is. The brew installed the libxml2 in /usr/local/Cellar/libxml2/2.9.3, but the configuring only looking into /usr/local/Cellar/libxml2. So there maybe another issue: how can I let the configure.py to look into the dirctory that brew installed the dependences?.

**Comment by jmansour** [comment]
You can run `./configure.py --help` to find out options, but I believe you require `--libxml2-dir=/usr/local/Cellar/libxml2`.  Depending on how the homebrew installation is setup, you may instead need to use `--libxml2-inc-dir=` and `--libxml2-lib-dir=` to point to the specific header/library directories. 

Which osx are you running?  Normally they have libxml2 installed in the standard locations.

**Comment by wkillers** [comment]
My osx is EI X Capitan 10.11.4. Maybe I should have set the environment variables instead.

**Comment by julesghub** [comment]
this might help
   `brew link libxml2`
it should symlink libxml2 to a more standard location.

Does `brew doctor` recommend anything as such?

**Comment by wkillers** [comment]
No, the 'brew doctor' don't recommend anything like that.

When I run 'brew link libxml2', there is a warning: libxml2 is keg-only and must be linked with --force, Note that doing so can interfere with building software.

**Comment by lmoresi** [comment]
I got caught by some new issues when I updated my machine today.

I built my own petsc and configured against that but for everything else, I was fine.

you can always point the configure script at the specific installation.

Look at configure.py —help to see all the options

L


On 30 March 2016 at 4:12:08 PM, wkillers (notifications@github.com<mailto:notifications@github.com>) wrote:

No, the 'brew doctor' don't recommend anything like that.

When I run 'brew link libxml2', there is a warning: libxml2 is keg-only and must be linked with --force, Note that doing so can interfere with building software.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/98#issuecomment-203251388>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by wkillers** [comment]
Thanks.

When configuring the petsc, another error appears: private/kspimpl.h file not found.

**Comment by lmoresi** [comment]
True, I hacked a bunch of stuff and I have asked Julian to see if there is a better way to do this.

Hold on !



On 30 March 2016 at 4:34:09 PM, wkillers (notifications@github.com<mailto:notifications@github.com>) wrote:

Thanks.

When configuring the petsc, another error appears: private/kspimpl.h file not found.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/98#issuecomment-203256016>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by wkillers** [comment]
Oops, hoping it will be worked out soon!

**Comment by julesghub** [comment]
@wkillers, 
re: petsc - you should be able to install it with brew using the following 
   `brew install petsc --without-mumps --without-metis --without-parmetis --without-superlu_dist`
   `export PETSC_DIR=/usr/local/opt/petsc`
note this will provide a petsc without some features we optionally use, e.g. no mumps solver. Give the brew devs a few weeks to fix the default petsc (feature rich) brew package.

re: libxml2
once libxml2 is installed with brew, i.e., `brew install libxml2`
point underworld's configuration script to it , as the other suggested
`./configure --libxml2-dir=/usr/local/opt/libxml2`

**Comment by wkillers** [comment]
@julesghub ,

Thanks. This make the installation of petsc works, and the configuration looks like succeed. But when I run './scons.py', some errors appear to stop the buildings:
SHANs-iMac:libUnderworld apple$ ./scons.py 
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/viewer.cfg", "viewer.cfg")
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:356:29: warning: incompatible pointer types passing
      'PetscScalar *' (aka '_Complex double *') to parameter of type 'PetscReal *' (aka 'double *')
      [-Wincompatible-pointer-types]
    MatNorm(G,NORM_INFINITY,&gnorm);
                            ^~~~~~
/usr/local/opt/petsc/complex/include/petscmat.h:475:61: note: passing argument to parameter here
PETSC_EXTERN PetscErrorCode MatNorm(Mat,NormType,PetscReal *);
                                                            ^
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:357:28: warning: incompatible pointer types passing
      'PetscScalar *' (aka '_Complex double *') to parameter of type 'PetscReal *' (aka 'double *')
      [-Wincompatible-pointer-types]
    VecNorm(h_hat, NORM_2, &hnorm);
                           ^~~~~~
/usr/local/opt/petsc/complex/include/petscvec.h:216:61: note: passing argument to parameter here
PETSC_EXTERN PetscErrorCode VecNorm(Vec,NormType,PetscReal *);
                                                            ^
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:360:15: error: invalid operands to binary expression
      ('PetscScalar' (aka '_Complex double') and 'double')
    if((hnorm < 1e-6) && (hnorm > 1e-20)){
        ~~~~~ ^ ~~~~
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:360:33: error: invalid operands to binary expression
      ('PetscScalar' (aka '_Complex double') and 'double')
    if((hnorm < 1e-6) && (hnorm > 1e-20)){
                          ~~~~~ ^ ~~~~~
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:384:15: error: invalid operands to binary expression
      ('PetscScalar' (aka '_Complex double') and 'double')
    if((hnorm < 1e-6) && (hnorm > 1e-20)){
        ~~~~~ ^ ~~~~
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:384:33: error: invalid operands to binary expression
      ('PetscScalar' (aka '_Complex double') and 'double')
    if((hnorm < 1e-6) && (hnorm > 1e-20)){
                          ~~~~~ ^ ~~~~~
2 warnings and 4 errors generated.
scons: *** [build/Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.os] Error 1
scons: building terminated because of errors.

How to solve such kind of problem? Thank you for your help.

**Comment by lmoresi** [comment]
Brew will install both real and complex versions of petsc. I think we assume real.

You just have to be sure to use the correct PETSC_DIR.

> brew info petsc will tell you the two possible choices for this environment variable


On 31 March 2016 at 7:37:07 pm, wkillers (notifications@github.com<mailto:notifications@github.com>) wrote:

@julesghub<https://github.com/julesghub> ,

Thanks. This make the installation of petsc works, and the configuration looks like succeed. But when I run './scons.py', some errors appear to stop the buildings:
SHANs-iMac:libUnderworld apple$ ./scons.py
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/viewer.cfg", "viewer.cfg")
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:356:29: warning: incompatible pointer types passing
'PetscScalar ' (aka '_Complex double *') to parameter of type 'PetscReal *' (aka 'double *')
[-Wincompatible-pointer-types]
MatNorm(G,NORM_INFINITY,&gnorm);
^~~~~~
/usr/local/opt/petsc/complex/include/petscmat.h:475:61: note: passing argument to parameter here
PETSC_EXTERN PetscErrorCode MatNorm(Mat,NormType,PetscReal *);
^
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:357:28: warning: incompatible pointer types passing
'PetscScalar *' (aka '_Complex double *') to parameter of type 'PetscReal *' (aka 'double *')
[-Wincompatible-pointer-types]
VecNorm(h_hat, NORM_2, &hnorm);
^~~~~~
/usr/local/opt/petsc/complex/include/petscvec.h:216:61: note: passing argument to parameter here
PETSC_EXTERN PetscErrorCode VecNorm(Vec,NormType,PetscReal *);
^
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:360:15: error: invalid operands to binary expression
('PetscScalar' (aka '_Complex double') and 'double')
if((hnorm < 1e-6) && (hnorm > 1e-20)){
~~~~~ ^ ~~~~
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:360:33: error: invalid operands to binary expression
('PetscScalar' (aka '_Complex double') and 'double')
if((hnorm < 1e-6) && (hnorm > 1e-20)){
~~~~~ ^ ~~~~~
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:384:15: error: invalid operands to binary expression
('PetscScalar' (aka '_Complex double') and 'double')
if((hnorm < 1e-6) && (hnorm > 1e-20)){
~~~~~ ^ ~~~~
Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.c:384:33: error: invalid operands to binary expression
('PetscScalar' (aka '_Complex double') and 'double')
if((hnorm < 1e-6) && (hnorm > 1e-20)){
~~~~~ ^ ~~~~~
2 warnings and 4 errors generated.
scons: ** [build/Solvers/KSPSolvers/src/BSSCR/auglag-driver-DGTGD.os] Error 1
scons: building terminated because of errors.

How to solve such kind of problem? Thank you for your help.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/98#issuecomment-203820960>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by wkillers** [comment]
It seems that this problem comes out is because I changed the mpi path that point to another version of mpi. Now the configuration and buildings are all right.

**Comment by julesghub** [comment]
Great news! I'll close this ticket. 
Good luck uw2 and remember to try re-installing petsc after a brew update in a few weeks.
